### ISSUE TITLE
Fails when loading custom .babelrc from a scoped dependency

### ISSUE THREAD

**Issue by NameFILIP** [storybooks/storybook#1095]
My `my-project/.babelrc` contains:
```
{
  "extends": "@my-scope/tasks/.babelrc",
  ...
}
```
When I run `yarn storybook`, I receive a message:
```
ERROR in ./.storybook/config.js
Module build failed: Error: [BABEL] /Users/myusername/Dev/my-project/.storybook/config.js: Couldn't resolve extends clause of /Users/myusername/Dev/my-project/@my-scope/tasks/.babelrc in base
    at Logger.error (/Users/myusername/Dev/my-project/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at ConfigChainBuilder.mergeConfig (/Users/myusername/Dev/my-project/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:186:32)
    at buildConfigChain (/Users/myusername/Dev/my-project/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:64:11)
    at OptionManager.init (/Users/myusername/Dev/my-project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
    at File.initOptions (/Users/myusername/Dev/my-project/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/myusername/Dev/my-project/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/myusername/Dev/my-project/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/myusername/Dev/my-project/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/Users/myusername/Dev/my-project/node_modules/babel-loader/lib/index.js:163:20)
 @ multi preview
```
As you can see, it's looking for the .`babelrc` in `my-project/@my-scope/tasks/.babelrc` while it should be looking it in the node_modules: `my-project/node_modules/@my-scope/tasks/.babelrc`

**Comment by NameFILIP** [comment]
A workaround for this is to change the extends property to:
```
{
  "extends": "./node_modules/@my-scope/tasks/.babelrc",
  ...
}
```
but it would be nice to fix the issue.

**Comment by ndelangen** [comment]
I'm super glad you found a work-around that works for you.

We're gonna fix this, thanks for reporting!

**Comment by zeroasterisk** [comment]
I too am having this problem in a Meteor project.

I've been renaming the `.bablerc` file when starting storybook, which is a terrible plan.

In a meteor application, there is no `.babelrc` file... it's handled inside meteor... but it now respects the  `.babelrc` file, and storybook's file is "messing up" meteor.

**Comment by ndelangen** [comment]
@zeroasterisk Sorry this isn't super high on our roadmap, I think it could be quite complicated to solve, but of course anyone is open to try. So if you want, a PR is welcome!

I can think of a method to fix your problem I think: Place your storybook next to (outside of) your meteor src-folder?

**Comment by danielduan** [comment]
you can also try using `require.resolve('babel-plugin-name')` in the `.babelrc` as well.

**Comment by likethemammal** [comment]
I came here cus the .babelrc react-static creates uses `extends` and causes this issue with storybook. For other ppl that land here for the same reason, the workaround from @NameFILIP worked for me.
