### ISSUE TITLE
error following the slow start guide

### ISSUE THREAD

**Issue by wildeyes** [storybooks/storybook#1106]
I am following the slow start guide (the quickstart failed ):
`npm run storybook`
gets me
```
ERROR in ./.storybook/config.js
Module build failed: TypeError: The plugin ["C:\\code\\node_modules\\babel-plugin-react-docgen\\lib\\index.js",{"DOC_GEN_COLLECTION_NAME":"STORYBOOK_REACT_CLASSES"}] didn't export a Plugin instance
    at PluginManager.validate (C:\code\node_modules\babel-core\lib\transformation\file\plugin-manager.js:164:13)
    at PluginManager.add (C:\code\node_modules\babel-core\lib\transformation\file\plugin-manager.js:213:10)
    at File.buildTransformers (C:\code\node_modules\babel-core\lib\transformation\file\index.js:237:21)
    at new File (C:\code\node_modules\babel-core\lib\transformation\file\index.js:139:10)
    at Pipeline.transform (C:\code\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
    at transpile (C:\code\node_modules\babel-loader\lib\index.js:46:20)
    at Object.module.exports (C:\code\node_modules\babel-loader\lib\index.js:163:20)
 @ multi preview
```
This is an internal storybook module, and it seems to be exporting a Plugin instance.
Looking at the code in `plugin-manager`, seems `plugin.buildPass` is undefined, thus tripping the failure.

Why?

**Comment by UsulPro** [comment]
Hi @wildeyes I wonder what reason that quickstart failed? Possible you have an issue with `getstorybook` cli? I just went through the installation process, so may I offer this short guide how to install Storybook Alpha on Windows. You will need `yarn` for that.

Follow this steps:

```shell
create-react-app alpha_test
yarn add @storybook/cli --dev
node_modules\.bin\getstorybook
```
You'll see such output:

```shell
λ node_modules\.bin\getstorybook.cmd                                      
                                                                          
 getstorybook - the simplest way to add a storybook to your project.      
                                                                          
 • Detecting project type. ✓                                              
 • Adding storybook support to your "Create React App" based project. ✓   
 • Preparing to install dependencies. ✓                                   
                                                                          
                                                                          
 • Installing dependencies. ✖                                             
                                                                          
     An error occurred while installing dependencies.                     
```                                                                          

Don't worry, type:
```shell
yarn
```

You will see this warning:
```
λ yarn
yarn install v0.19.1
[1/4] Resolving packages...
Couldn't find any versions for "@storybook/react" that matches "^2.21.0"
? Please choose a version from this list: (Use arrow keys)
> 3.0.0-alpha.4
  3.0.0-alpha.3
  3.0.0-alpha.1
  3.0.0-alpha.0
```

It's Okey, just select the latest version. (I choosed alpha.4)
Then process should go fine. 
**Note**: if you use `npm` you'll have an error on this step.

Final step:

```shell
yarn run storybook
```

After you see:
```
λ yarn run storybook
yarn run v0.19.1
$ start-storybook -p 9009 -s public
@storybook/react v3.0.0-alpha.4

=> Loading static files from: E:\DevelopWeb\_Storybook\sandbox\alpha_test\public .
=> Loading custom addons config.
=> Using default webpack setup based on "Create React App".
Storybook started on => http://localhost:9009/

webpack built bf31959bcebbd35c5a25 in 4760ms
```
open in your browser http://localhost:9009

**Comment by ndelangen** [comment]
Please install the last alpha version:
`npm i @storybook/cli@alpha -g`

**Comment by shilman** [comment]
@wildeyes closing for now, please reopen if the latest alpha doesn't fix your issue!
