### ISSUE TITLE
build-storybook (v3) doesn't work anymore

### ISSUE THREAD

**Issue by dangreen** [storybooks/storybook#1203]
In my configuration i inject some loaders into `module.rules`, it perfectly works with `start-storybook`. `build-storybook` v2 also works perfectly: it compile and copy all assets into build dir.
With v3: it doesn't copy assets anymore.

Also in browser i have this issue (node-sass? wtf??):
```
Uncaught Error: Module build failed: Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.5.2
    at module.exports (/Users/dangreen/github/leadcooker2/new-frontend/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/dangreen/github/leadcooker2/new-frontend/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:569:30)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/dangreen/github/leadcooker2/new-frontend/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at module.exports (/Users/dangreen/github/leadcooker2/new-frontend/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/dangreen/github/leadcooker2/new-frontend/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:569:30)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/dangreen/github/leadcooker2/new-frontend/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.freeExports (http://develop.trigen.pro/leadcooker-ui/static/preview.1a904cf1fa11c8c72bc5.bundle.js:73155:7)
    at __webpack_require__ (http://develop.trigen.pro/leadcooker-ui/static/preview.1a904cf1fa11c8c72bc5.bundle.js:20:30)
    at Object.<anonymous> (http://develop.trigen.pro/leadcooker-ui/static/preview.1a904cf1fa11c8c72bc5.bundle.js:80504:15)
    at __webpack_require__ (http://develop.trigen.pro/leadcooker-ui/static/preview.1a904cf1fa11c8c72bc5.bundle.js:20:30)
    at Object.<anonymous> (http://develop.trigen.pro/leadcooker-ui/static/preview.1a904cf1fa11c8c72bc5.bundle.js:64909:73)
    at Object.defineProperty.value (http://develop.trigen.pro/leadcooker-ui/static/preview.1a904cf1fa11c8c72bc5.bundle.js:64938:30)
    at __webpack_require__ (http://develop.trigen.pro/leadcooker-ui/static/preview.1a904cf1fa11c8c72bc5.bundle.js:20:30)
    at Object.<anonymous> (http://develop.trigen.pro/leadcooker-ui/static/preview.1a904cf1fa11c8c72bc5.bundle.js:80939:18)
    at __webpack_require__ (http://develop.trigen.pro/leadcooker-ui/static/preview.1a904cf1fa11c8c72bc5.bundle.js:20:30)
    at http://develop.trigen.pro/leadcooker-ui/static/preview.1a904cf1fa11c8c72bc5.bundle.js:66:18
```

**Comment by ndelangen** [comment]
What loaders are you injecting?

**Comment by dangreen** [comment]
```js
[{
	test: /\.scss$/,
	use: [{
		loader: 'style-loader'
	}, {
		loader:  'css-loader',
		options: {
			importLoaders: 1
		}
	}, {
		loader: 'postcss-loader',
		options: {
			plugins: () => [
				autoprefixer(autoprefixerConfig)
			]
		}
	}, {
		loader:  'resolve-url-loader',
		options: {
			sourceMap: true,
			keepQuery: true
		}
	}, {
		loader:  'sass-loader',
		options: {
			sourceMap: true
			// includePaths: [path.join(cwd, paths.src.app, 'ui-customize')]
		}
	}]
}, {
	test: /\.svg$/,
	use:  [{
		loader:  'svg-sprite-loader',
		options: {
			runtimeGenerator: path.join(cwd, 'tasks/helpers/svg-to-component.js'),
			runtimeOptions:   {
				iconModule: path.join(cwd, paths.src.app, 'ui/components/icon/icon.js')
			}
		}
	}]
}, {
	test:   /\.(eot|woff|ttf)$/,
	loader: 'file-loader'
}]

**Comment by danielduan** [comment]
Node 8 is the `unsupported runtime`. Looks like they support only up to 7.
https://github.com/sass/node-sass/releases/tag/v4.5.2

**Comment by ndelangen** [comment]
It's possible got get working. Can you confirm it does work in node < 8 ?

**Comment by dangreen** [comment]
@ndelangen with node v7 all works.

**Comment by ndelangen** [comment]
I'm not sure what to do, I'm not faced with this error on my machine, and I'm running Node 8.0.3.
`node-sass` should support node 8 now: https://github.com/sass/node-sass/issues/1985

**Comment by danielduan** [comment]
@dangreen try upgrading the `sass-loader` and `node-sass` to the latest and see if that at least fixes the sass problem for you?

**Comment by dangreen** [comment]
@danielduan i'm already have latest version of sass-loader

**Comment by ndelangen** [comment]
Do you have a repository we can use to reproduce the issue?

**Comment by BerndWessels** [comment]
Maybe related to [this issue](https://github.com/storybooks/storybook/issues/1362).

**Comment by alloy** [comment]
I think we’re having the same issue as OP, here’s a repo to reproduce with: https://github.com/artsy/reaction-force.

**Comment by danielduan** [comment]
If this is still an issue on the latest versions, please reopen.
