### ISSUE TITLE
Not able to run storybook

### ISSUE THREAD

**Issue by Balasnest** [storybooks/storybook#1319]
I cannot able to connect with local host in react-native. I have created .storybook/config.js also. What would be the problem? 
> start-storybook -p 7007 -c .storybook

@storybook/react v3.1.3

=> Loading custom .babelrc
=> Using default webpack setup based on "Create React App".
 10% building modules 2/2 modules 0 activeevents.js:182    c       throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::7007
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server.setupListenHandle [as _listen2] (net.js:1305:14)
    at listenInCluster (net.js:1353:12)
    at Server.listen (net.js:1453:7)
    at Function.listen (/Users/sumit/Desktop/React Native/Albums-react-native/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/Users/sumit/Desktop/React Native/Albums-react-native/node_modules/@storybook/react/dist/server/index.js:160:27)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Albums@0.0.1 storybook: `start-storybook -p 7007 -c .storybook`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Albums@0.0.1 storybook script.

**Comment by marc-rutkowski** [comment]
@Balasnest the ```EADDRINUSE``` error means that the local specified port (7007) is already used by another instance of a server.
Try to kill other instances or choose a different port number.
