### ISSUE TITLE
Storybook/CreateReactApp can't use addons

### ISSUE THREAD

**Issue by natdm** [storybooks/storybook#1322]
I seem to be having issues with any addons I use. Here is how I am using the actions and notes addons...

`package.json`:
```javascript
"devDependencies": {
    "@kadira/storybook": "^2.35.3",
    "@storybook/addon-actions": "^3.1.2",
    "@storybook/addon-notes": "^3.1.2",
    "@storybook/react": "3.1.3",
    "babel-preset-es2017": "^6.24.1",
    "faker": "^4.1.0",
    "flow-bin": "^0.47.0",
    "react-scripts": "0.9.5",
    "storybook": "^0.0.0",
    "storybook-addon-specifications": "^2.1.0"
  },
```

First, actions:

Here is my story:
```javascript
import React from 'react';
import { storiesOf } from '@kadira/storybook';
import { action } from '@storybook/addon-actions';

import { ItemCreateModalForm } from './index';

// Any redux form needs wrapped in the provider and the store.
import { Provider } from 'react-redux';
import { fakeStore } from '../../store';

storiesOf('ItemCreateModal', module).add('basic', () => {
    return (
        <Provider store={fakeStore('', null)}>
            <ItemCreateModalForm
                handleClose={() => {
                    console.log('clicked');
                    action('asdf');
                }}
                open
            />
        </Provider>
    );
});

```

Here is my `.storybook/addons.js`
```javascript
import '@storybook/addon-actions/register';
```
When I click the button that would run `handleClose`, it will log "clicked" to the console but won't do anything with the action

I do get the action panel at the bottom of the screen, but no actions logged, and no errors or anything in console.

I am not sure if it's of any consequence but I can't use the notes addon either.
After adding the `addon-notes` to the `addons.js` file and changing code to this, and restarting, I get 
```
Cannot read property 'emit' of null
TypeError: Cannot read property 'emit' of null
    at WithNotes.render (http://localhost:9009/0.9322d942c70d057ae995.hot-update.js:66:14)
    at http://localhost:9009/static/preview.bundle.js:39553:21
    at measureLifeCyclePerf (http://localhost:9009/static/preview.bundle.js:38832:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (http://localhost:9009/static/preview.bundle.js:39552:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (http://localhost:9009/static/preview.bundle.js:39579:32)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:9009/static/preview.bundle.js:39119:30)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:9009/static/preview.bundle.js:39015:21)
    at Object.mountComponent (http://localhost:9009/static/preview.bundle.js:8802:35)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:9009/static/preview.bundle.js:39128:34)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:9009/static/preview.bundle.js:39015:21)
```

Erroring code: 
```javascript
import React from 'react';
import { storiesOf } from '@kadira/storybook';
import { action } from '@storybook/addon-actions';
import { WithNotes } from '@storybook/addon-notes';

import { ItemCreateModalForm } from './index';

// Any redux form needs wrapped in the provider and the store.
import { Provider } from 'react-redux';
import { fakeStore } from '../../store';

storiesOf('ItemCreateModal', module).add('basic', () => {
    return (
        <WithNotes note={'asdf'}>
            <Provider store={fakeStore('', null)}>
                <ItemCreateModalForm
                    handleClose={() => {
                        console.log('clicked');
                        action('asdf');
                    }}
                    open
                />
            </Provider>
        </WithNotes>
    );
});
```

I have also tried moving the `WithNotes` component to the inside of the Provider but same result.

I need provider for this component because it utilizes `redux-form`, if anyone was wondering.

**Comment by xavcz** [comment]
👋 hey, thanks for filing an issue!

It looks like you mix the old version of storybook and the new version. 

Instead of importing `storiesOf` from `@kadira/storybook`, you'd want import it from `@storybook/react`, like [in this example](https://github.com/storybooks/storybook/blob/master/examples/cra-kitchen-sink/src/stories/index.js#L4).

```js
import { storiesOf } from '@storybook/react';
```

The new addon may not be able to communicate with the "old" structure 😄 You don't need any more `@kadira/storybook` in your `package.json` (and also this `"storybook": "^0.0.0"` 🤔 )

By the way, it's pretty neat to put the `<Provider />` in a decorator ([docs](https://storybook.js.org/addons/introduction/#storybook-decorators))with `.addDecorator` so you can reuse it for any story you want.

**Comment by UsulPro** [comment]
In addition:
There is a [section](https://github.com/storybooks/storybook/blob/master/MIGRATION.md#packages-renaming) with new package names in the MIGRATION guide

**Comment by natdm** [comment]
All this was fantastic. Thanks @UsulPro  and @xavcz !!!
