### ISSUE TITLE
TypeError: chunk.sortModules is not a function

### ISSUE THREAD

**Issue by WellerQu** [storybooks/storybook#1500]
I got an following error. I think it's because of the version of extract-text-webpack-plugin@3.0.0 . but extract-text-webpack-plugin@2.1.2 is no problem. Could you help me to upgrade extract-text-webpack-plugin in storybook? 

```
$ start-storybook -p 9001 -c build                                                                                                                                                                          @storybook/react v3.1.7
=> Loading custom .babelrc                                                                                                                                                                                  => Loading custom webpack config (full-control mode).
 78% advanced chunk optimization/Users/qiuwei/Workspace/rongcaptial-ui/node_modules/extract-text-webpack-plugin/dist/index.js:188
            chunk.sortModules();                                                                                                                                                                                              ^
TypeError: chunk.sortModules is not a function                                                                                                                                                                  at /Users/qiuwei/Workspace/rongcaptial-ui/node_modules/extract-text-webpack-plugin/dist/index.js:188:19
    at /Users/qiuwei/Workspace/rongcaptial-ui/node_modules/async/dist/async.js:3083:16
    at eachOfArrayLike (/Users/qiuwei/Workspace/rongcaptial-ui/node_modules/async/dist/async.js:1003:9)                                                                                                         at eachOf (/Users/qiuwei/Workspace/rongcaptial-ui/node_modules/async/dist/async.js:1051:5)                                                                                                                  at Object.eachLimit (/Users/qiuwei/Workspace/rongcaptial-ui/node_modules/async/dist/async.js:3145:5)
    at Compilation.<anonymous> (/Users/qiuwei/Workspace/rongcaptial-ui/node_modules/extract-text-webpack-plugin/dist/index.js:184:27)                                                                           at Compilation.applyPluginsAsyncSeries (/Users/qiuwei/Workspace/rongcaptial-ui/node_modules/tapable/lib/Tapable.js:142:13)
    at Compilation.seal (/Users/qiuwei/Workspace/rongcaptial-ui/node_modules/@storybook/react/node_modules/webpack/lib/Compilation.js:579:8)
    at /Users/qiuwei/Workspace/rongcaptial-ui/node_modules/@storybook/react/node_modules/webpack/lib/Compiler.js:493:16                                                                                         at /Users/qiuwei/Workspace/rongcaptial-ui/node_modules/tapable/lib/Tapable.js:225:11
```

**Comment by WellerQu** [comment]
OK, I upgrade @storybook/react, All fixed. Sorry to trouble you but thank you
