### ISSUE TITLE
Build Storybook command is failing:

### ISSUE THREAD

**Issue by benbayard** [storybooks/storybook#1563]
```
Error: Cannot find module 'webpack/lib/RequestShortener'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ubuntu/ui/node_modules/uglifyjs-webpack-plugin/dist/index.js:17:24)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! storybook:build: `build-storybook -o storybook-static`
````

**Comment by psimyn** [comment]
this looks like you are missing webpack as a dependency - is it included in your package.json?

If so, can you try running `npm install` again?

**Comment by danielduan** [comment]
if this is still an issue, please reopen.

**Comment by tcg** [comment]
Howdy! I just ran into this exact thing (thanks Google for finding this issue!). 

Running `npm install webpack --save-dev` solved it for me. 

I'm still a bit of a noob w/ npm deps, etc. Does it seem correct that I should have had to do it that way? 

Is this maybe because of a difference in npm/yarn installs? I see the README uses yarn.

**Comment by danielduan** [comment]
You shouldn't need to install it because it's already installed as part of the dependencies for `@storybook/react`. I'm on `npm@5.4` and `node@8.9` if that makes a difference.

Also, the storybook command should be called from the same directory as where storybooks is installed.
