### ISSUE TITLE
Global decorators cause Storyshots to fail

### ISSUE THREAD

**Issue by duro** [storybooks/storybook#1625]
Surfacing this again from #877.

When I add a global decorator to `.storybook/config.js` it cuases my Storyshot tests to fail with:

```
src/components/__test__/Storyshots.test.js
  ● Test suite failed to run

    Global decorators added after loading stories will not be applied

      at ClientApi.addDecorator (node_modules/@storybook/react/dist/client/preview/client_api.js:55:15)
      at evalmachine.<anonymous>:13:25
      at runWithRequireContext (node_modules/@storybook/addon-storyshots/dist/require_context.js:102:3)
      at testStorySnapshots (node_modules/@storybook/addon-storyshots/dist/index.js:100:35)
      at Object.<anonymous> (src/components/__test__/Storyshots.test.js:3:31)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by evenchange4** [comment]
Here is a simple workaround which mocking `addDecorator` as an emptyFunction for my project.

```js
// Storyshots.test.js
const sbReact = require('@storybook/react')
sbReact.addDecorator = () => {}

initStoryshots()
```
