### ISSUE TITLE
Add `latest-version` to `/lib/cli/package.json`

### ISSUE THREAD

**Issue by vjpr** [storybooks/storybook#1671]
Dependency used without being declared in pjson.

```
Error: Cannot find module 'latest-version'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/Vaughan/nvm/versions/node/v8.1.2/pnpm-global/1/node_modules/.registry.npmjs.org/@storybook/cli/3.2.5/node_modules/@storybook/cli/generators/WEBPACK_REACT/index.js:4:23)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by Hypnosphi** [comment]
Fixed in `3.2.7`
