### ISSUE TITLE
Global addDecorator not loaded

### ISSUE THREAD

**Issue by creaux** [storybooks/storybook#1755]
I see you already trying to solve this issue here #879 but I experiencing maybe the same. I haven't digged into deeply but following code making issue.

```javascript
import withThemes from './decorators/withThemes';
...
const spread = require.context('../app', true, /stories.jsx?$/);
...
addDecorator(withThemes);
...
function loadStories() {
  spread.keys().forEach(filename => spread(filename));
}

configure(loadStories, module);
```

Error is following...

```bash
[withTheme] Please use ThemeProvider to be able to use withTheme
      
      at WithTheme.componentWillMount (node_modules/styled-components/lib/hoc/withTheme.js:63:15)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:348:23
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
      at ReactCompositeComponent.performInitialMount (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:347:9)
      at ReactCompositeComponent.mountComponent (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:258:21)
      at Object.ReactReconciler.mountComponent (node_modules/react-test-renderer/lib/ReactReconciler.js:46:35)
      at ReactCompositeComponent.performInitialMount (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:371:34)
      at ReactCompositeComponent.mountComponent (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:258:21)
      at Object.ReactReconciler.mountComponent (node_modules/react-test-renderer/lib/ReactReconciler.js:46:35)
      at mountComponentIntoNode (node_modules/react-test-renderer/lib/ReactTestMount.js:55:31)
      at ReactTestReconcileTransaction.TransactionImpl.perform (node_modules/react-test-renderer/lib/Transaction.js:140:20)
      at batchedMountComponentIntoNode (node_modules/react-test-renderer/lib/ReactTestMount.js:69:27)
      at ReactDefaultBatchingStrategyTransaction.TransactionImpl.perform (node_modules/react-test-renderer/lib/Transaction.js:140:20)
      at Object.ReactDefaultBatchingStrategy.batchedUpdates (node_modules/react-test-renderer/lib/ReactDefaultBatchingStrategy.js:62:26)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactUpdates.js:97:27)
      at Object.ReactTestMount.render [as create] (node_modules/react-test-renderer/lib/ReactTestMount.js:125:18)
      at Object.test (node_modules/@storybook/addon-storyshots/dist/test-bodies.js:26:44)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/index.js:141:21)
      at process._tickCallback (internal/process/next_tick.js:103:7)

```

I'm using `styled-components` which expecting that I will use with HOC from this is quiet straightforward that hoc is not able to gather context data properly.

**Comment by UsulPro** [comment]
@creaux did you try to put `addDecorator` inside `loadStories()` as a workaround:

```js
function loadStories() {
  addDecorator(withThemes);
  spread.keys().forEach(filename => spread(filename));
}
```

**Comment by creaux** [comment]
it didn't help.

**Comment by creaux** [comment]
Okay I did directly this in decorator and it didn't helped.

```javascript
return <ThemeProvider theme={this.theme}>{children}</ThemeProvider>;
```

So seems to be really somewhere else.

**Comment by creaux** [comment]
When I'm using addDecorator per each story it works!

```javascript
storiesOf('Pager')
  .addDecorator(themeProvider(theme))
  .add('story', () => (
    <Component {...props1} />
  ));
```

Any thoughts?

**Comment by UsulPro** [comment]
@creaux I tried to reproduce with `@storybook/react v3.2.8` such a simple global decorator:

```js
addDecorator(storyFn => <div style={{border: 'solid 10px navy'}} children={storyFn()} />);
```

and it works fine for me. 
What version of Storybook do you use at this moment?
Could you try to add this line into your `config.js` and check it out? Please, make sure that you manually update the page after each change since HMR doesn't do it for a config files.

**Comment by creaux** [comment]
Hello @UsulPro, thanks for reply. I have update regarding issue which is at the moment permanent.

Global decorator is **not loaded only for JEST storyshots**. I overstepped this issue by local decorator which is passthrough as empty function for storybook (as global decorator is working) but local is only loaded for storyshots in JEST environment.

```javascript
storiesOf('Component')
  // For storybook passthrough function returning getStory()
  // For jest HOC containing ThemeProvider encapsulation
  .addDecorator(themeProvider(theme)))
  .add('story', () => (
    <Component {...props} />
  ))
```

Global provider still used but changed as I was bit unclear about element vs. component and how storybook handling it (that was reason of previous issue). Now it is clear and usage is following.

```javascript
class WithTheme extends Component {
   ...
   render() {
       ...
       return <ThemeProvider theme={this.theme}>{children}</ThemeProvider>;
  }
}
```
