### ISSUE TITLE
Storybook doesn't work with Create React App project (React 16).

### ISSUE THREAD

**Issue by bermanboris** [storybooks/storybook#1935]
After installing storybook into existing CRA (Create React App) project and going to http://localhost:9009/, storybook crashes with the next error:

```javascript
Cannot read property 'string' of undefined
TypeError: Cannot read property 'string' of undefined
    at Object.<anonymous> (http://localhost:9009/static/preview.bundle.js:44726:69)
    at __webpack_require__ (http://localhost:9009/static/preview.bundle.js:678:30)
    at fn (http://localhost:9009/static/preview.bundle.js:88:20)
    at Object.<anonymous> (http://localhost:9009/static/preview.bundle.js:44667:66)
    at Object.<anonymous> (http://localhost:9009/static/preview.bundle.js:44691:30)
    at __webpack_require__ (http://localhost:9009/static/preview.bundle.js:678:30)
    at fn (http://localhost:9009/static/preview.bundle.js:88:20)
    at loadStories (http://localhost:9009/static/preview.bundle.js:41741:3)
    at ConfigApi._renderMain (http://localhost:9009/static/preview.bundle.js:42751:20)
    at render (http://localhost:9009/static/preview.bundle.js:42777:17)
```

I think Storybook tries to read PropTypes from the react package, and as far as I know, PropTypes were removed completely from React 16.  

Any was I can solve this issue? Thanks!

**Comment by Hypnosphi** [comment]
Which version of `@storybook/react` do you use?

**Comment by bermanboris** [comment]
@Hypnosphi, 3.2.11

**Comment by bermanboris** [comment]
I found the issue! 

I've installed and ran old version of storybook first. It created default stories with depricated PropTypes. Upgrading to newest version of storybook didn't helped, because it didn't override the stories directory in src. 

Deleting `src/stories` and running `getstorybook -f` helped. 

Thanks!
