### ISSUE TITLE
Not working with webpack config resolve.alias

### ISSUE THREAD

**Issue by AshCoolman** [storybooks/storybook#2011]
I setup storyshots for the first time. While react storybook works, storyshots does not respect the resolve aliases in my webpack config. I believe I have a very standard setup

Package versions:
```
react: 15.6.2
jest: 21.0.2
webpack 3.6.0
@storybook/addon-storyshots: 3.2.12
@storybook/react: 3.2.11
```

_/Storyshots.test.js_
```
import initStoryshots from '@storybook/addon-storyshots';

initStoryshots();
```

_/webpack.config.dev.js_ snippet
```
  resolve: {
    extensions: ['.js', '.jsx'],
    alias: {
      components: path.resolve(__dirname, 'src/components/'),
      containers: path.resolve(__dirname, 'src/containers/'),
      utils: path.resolve(__dirname, 'src/utils/'),
    },
  },
```

_/.storybook/webpack.config.js_
```
const projWebpack = require('../webpack.config.dev');
module.exports = (sbConfig, type) => {
  sbConfig.resolve.alias = projWebpack.resolve.alias;
  return sbConfig;
}
```

Error output

```
 FAIL  ./Storyshots.test.js
  ● Test suite failed to run

    Cannot find module 'components/FullscreenCarousel' from 'index.jsx'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:191:17)
      at Object.<anonymous> (src/components/ListingCarousel/index.jsx:15:27)
```

Can anyone see anything wrong here?

**Comment by AshCoolman** [comment]
Actually, looks like Jest setup issue. 
Should be nothing to do with Storyshot

**Comment by giovannibenussi** [comment]
It is a Jest configuration issue. I solved it by adding the following to my `package.json`:

```
"jest": {
  "moduleNameMapper": {
    "^components(.*)$": "<rootDir>/src/components$1"
}
```
