### ISSUE TITLE
Storyshots is broken with React 16

### ISSUE THREAD

**Issue by eddiemonge** [storybooks/storybook#2021]
Running Snapshots with React 16 fails due to `Cannot read property 'ReactCurrentOwner' of undefined`

I created a simple repo here for this https://github.com/eddiemonge/snapshots-broken

Here's the full output

```
 FAIL  ./snapshots.js
  ● Test suite failed to run

    TypeError: Cannot read property 'ReactCurrentOwner' of undefined

      at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:621:36
      at Object.<anonymous> (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8254:3)
      at Object.<anonymous> (node_modules/react-test-renderer/index.js:6:20)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/test-bodies.js:10:26)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/index.js:12:19)
      at Object.<anonymous> (snapshots.js:1:113)
          at Generator.next (<anonymous>)
          at Promise (<anonymous>)
      at handle (node_modules/worker-farm/lib/child/index.js:44:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:51:3)
      at emitTwo (events.js:125:13)
      at process.emit (events.js:213:7)
      at emit (internal/child_process.js:774:12)
      at _combinedTickCallback (internal/process/next_tick.js:141:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by eddiemonge** [comment]
Nevermind looks like a react-test-renderer-issue

**Comment by zvictor** [comment]
I had the same problem. In my case I had `react-test-renderer@16` installed along with `react@15`. Downgrading to `react-test-renderer@15` solved the issue for me.

**Comment by rsimsek** [comment]
I have react@16 and  react-test-renderer@16 and still fails. 

```
 ● Test suite failed to run

    TypeError: Cannot read property 'ReactCurrentOwner' of undefined

      at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:77:39
      at Object.<anonymous> (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7676:5)
      at Object.<anonymous> (node_modules/react-test-renderer/index.js:6:20)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/test-bodies.js:10:26)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/index.js:12:19)
      at Object.<anonymous> (.storybook/storyshots.test.js:1:126)
```

**Comment by Hypnosphi** [comment]
What does `npm list react` output for you?

**Comment by coreylight** [comment]
Getting the same issue.
```
TypeError: Cannot read property 'renderer' of undefined      
      at getRenderedTree (node_modules/@storybook/addon-storyshots/dist/test-bodies.js:30:22)
      at node_modules/@storybook/addon-storyshots/dist/test-bodies.js:46:16
      at Object.test (node_modules/@storybook/addon-storyshots/dist/test-bodies.js:65:33)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/index.js:174:28)
```

- `@storybook/addon-storyshots@3.3.3`
- `react@16.2.0`
- `react-test-renderer@16.2.0`

**Comment by magnusheino** [comment]
Same issue as @coreylight, quick workaround that works for me:

```
import initStoryshots from '@storybook/addon-storyshots';
import ShallowRenderer from 'react-test-renderer/shallow';

const shallowSnapshot = ({ story, context }) => {
  expect(new ShallowRenderer().render(story.render(context))).toMatchSnapshot();
};

initStoryshots({
  test: shallowSnapshot,
});
```

**Comment by coreylight** [comment]
Following up, cc @magnusheino 
In my case I am using the `multiSnapshotWithOptions()` test/option, and that seems to be even more complex to implement a shim for at the moment.
@eddiemonge can you reopen this?

**Comment by eddiemonge** [comment]
@coreylight thats a different issue ... although i am getting that as well

**Comment by eddiemonge** [comment]
although I fixed it by passing an empty config object to multi instead of no arguments:

```
initStoryshots({
  test: multiSnapshotWithOptions({})
})
```

**Comment by dmk255** [comment]
@eddiemonge I've attempted use your solution but now my snapshots are being added to the __snapshots__ directory in the same location as my Storyshots.test.js

>Storyshots.test.js
```JS
import initStoryshots, { multiSnapshotWithOptions } from '@storybook/addon-storyshots';

initStoryshots({
  test: multiSnapshotWithOptions({}),
});
```
