### ISSUE TITLE
addon-graphql flow extension errors. (react 16)

### ISSUE THREAD

**Issue by idkjs** [storybooks/storybook#2139]
I have add the [addons/graphq module](https://github.com/storybooks/storybook/tree/master/addons/graphql) to a project. Works great! My terminal is a mess though with flow errors. Also affect jest test per test run output below.

So the rendering is good but the you lose the tests....

Is this a known thing? If so what is the solution? Thank you.

- errors:
```sh
WARNING in ./node_modules/graphql-language-service-interface/dist/autocompleteUtils.js.flow
Module parse failed: Unexpected token (11:12)
You may need an appropriate loader to handle this file type.
|  */
|
| import type {GraphQLField, GraphQLSchema, GraphQLType} from 'graphql';
| import {isCompositeType} from 'graphql';
| import {
 @ ./node_modules/graphql-language-service-interface/dist ^.*$
 @ ./node_modules/graphql-language-service-interface/dist/GraphQLLanguageService.js
 @ ./node_modules/graphql-language-service-interface/dist/index.js
 @ ./node_modules/codemirror-graphql/hint.js
 @ ./node_modules/graphiql/dist/components/QueryEditor.js
 @ ./node_modules/graphiql/dist/components/GraphiQL.js
 @ ./node_modules/graphiql/dist/index.js
 @ ./node_modules/@storybook/addon-graphql/dist/preview.js
 @ ./node_modules/@storybook/addon-graphql/dist/index.js
 @ ./stories/graphql.stories.js
 @ ./stories/index.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js (webpack)-hot-middleware/client.js?reload=true ./.storybook/config.js
```

-jest test error
```sh
  ● Test suite failed to run

    /Users/shingdev/code/awesome-components-idkjs/node_modules/graphiql/graphiql.css:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){.graphiql-container,
                                                                                             ^

    SyntaxError: Unexpected token .

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
      at Object.<anonymous> (node_modules/@storybook/addon-graphql/dist/preview.js:27:1)
      at Object.<anonymous> (node_modules/@storybook/addon-graphql/dist/index.js:7:16)
```

**Comment by tujoworker** [comment]
+1

**Comment by danielduan** [comment]
It's been a while since GraphQL has been updated and we'd love some help. If you guys are willing to dig into the codebase a bit, we'd really appreciate some work on the addon.

**Comment by Chris502** [comment]
Has anyone found a fix for this? I have encountered the same issue in my project. It wont render in the storybook at all.
