### ISSUE TITLE
Fix react-native-vanilla tests so they actually test storybook

### ISSUE THREAD

**Issue by danielduan** [storybooks/storybook#2273]
Our test only tests if the example react-native starts and renders, not our Storybook installation.

We have to have the web UI of react-native storybook running in order to run tests. It's hard to do with jest.
```
   ● Console

    console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2053
      The above error occurred in one of your React components:
          in Unknown (created by StorybookUIHMRRoot)
          in StorybookUIHMRRoot

      Consider adding an error boundary to your tree to customize error handling behavior.
      You can learn more about error boundaries at https://fb.me/react-error-boundaries.

  ● renders correctly

    TypeError: _global.WebSocket is not a constructor

      at WebsocketTransport._connect (node_modules/@storybook/channel-websocket/dist/index.js:87:22)
      at new WebsocketTransport (node_modules/@storybook/channel-websocket/dist/index.js:43:10)
      at createChannel (node_modules/@storybook/channel-websocket/dist/index.js:110:19)
      at node_modules/@storybook/react-native/dist/preview/index.js:143:52
      at mountIndeterminateComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4356:15)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4557:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6529:16)
      at workLoop (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6638:28)
      at Object.invokeGuardedCallback$1 (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2159:10)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2106:29)

Error: Accessing nonexistent addons channel, see https://storybook.js.org/basics/faq/#why-is-there-no-addons-channel
    at AddonStore.getChannel (/Users/danielduan/Workspace/storybook/examples/react-native-vanilla/node_modules/@storybook/addons/dist/index.js:39:15)
    at setOptions (/Users/danielduan/Workspace/storybook/examples/react-native-vanilla/node_modules/@storybook/addon-options/dist/preview/index.js:37:34)
    at Timeout._onTimeout (/Users/danielduan/Workspace/storybook/examples/react-native-vanilla/storybook/storybook.js:16:29)
    at ontimeout (timers.js:471:11)
    at tryOnTimeout (timers.js:306:5)
    at Timer.listOnTimeout (timers.js:266:5)
```

**Comment by tmeasday** [comment]
@danielduan -- are you sure this isn't just because Jest doesn't provide a `WebSocket` implementation? `@storybook/react-native` uses `@storybook/channel-websocket`, which of course tries to setup a websocket, but perhaps we could mock it out?

**Comment by danielduan** [comment]
I'm not a react-native jest expert by any means and I haven't looked into this in detail yet. This issue is to raise the problem that there's a problem with our test.

**Comment by danielduan** [comment]
might not be relevant after https://github.com/storybooks/storybook/pull/3278
