### ISSUE TITLE
[Angular] Storybook doesn't work with typescript 2.6

### ISSUE THREAD

**Issue by user753** [storybooks/storybook#2719]
angular works fine with 2.6 but Storybook show some errors
```                       Asset       Size  Chunks                    Chunk Names
    static/manager.bundle.js    2.81 MB       0  [emitted]  [big]  manager
    static/preview.bundle.js    3.82 MB       1  [emitted]  [big]  preview
static/manager.bundle.js.map    3.43 MB       0  [emitted]         manager
static/preview.bundle.js.map    4.46 MB       1  [emitted]         preview
                  index.html    1.21 kB          [emitted]         
                 iframe.html  592 bytes          [emitted]         
 [337] ./node_modules/@storybook/angular/dist/server/config/polyfills.js 74 bytes {0} {1} [built]
 [561] multi ./.storybook/addons.js ./node_modules/@storybook/angular/dist/server/config/polyfills.js ./node_modules/@storybook/angular/dist/client/manager/index.js 52 bytes {0} [built]
 [562] ./.storybook/addons.js 150 bytes {0} [built]
 [563] ./node_modules/@storybook/addon-actions/register.js 30 bytes {0} [built]
 [564] ./node_modules/@storybook/addon-links/register.js 30 bytes {0} [built]
 [565] ./node_modules/@storybook/addon-notes/register.js 31 bytes {0} [built]
 [567] ./node_modules/@storybook/angular/dist/client/manager/index.js 423 bytes {0} [built]
 [793] ./node_modules/@storybook/angular/dist/client/manager/provider.js 3.31 kB {0} [built]
 [798] multi ./node_modules/@storybook/angular/dist/server/config/polyfills.js ./node_modules/@storybook/angular/dist/server/config/globals.js (webpack)-hot-middleware/client.js?reload=true ./.storybook/config.js 64 bytes {1} [built]
 [799] ./node_modules/@storybook/angular/dist/server/config/globals.js 107 bytes {1} [built]
 [800] (webpack)-hot-middleware/client.js?reload=true 7.35 kB {1} [built]
 [804] ./node_modules/strip-ansi/index.js 161 bytes {1} [built]
 [806] (webpack)-hot-middleware/client-overlay.js 2.21 kB {1} [built]
 [812] ./.storybook/config.js 427 bytes {1} [built]
 [878] ./stories .stories.ts$ 183 bytes {1} [built]
    + 871 hidden modules

ERROR in ./node_modules/@storybook/angular/dist/client/preview/angular/app.token.ts
Module build failed: Error: Typescript emitted no output for /home/user/projects/tests/sb/node_modules/@storybook/angular/dist/client/preview/angular/app.token.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader (/home/user/projects/tests/sb/node_modules/ts-loader/dist/index.js:47:15)
    at Object.loader (/home/user/projects/tests/sb/node_modules/ts-loader/dist/index.js:29:12)
 @ ./node_modules/@storybook/angular/dist/client/preview/angular/helpers.ts 10:18-40
 @ ./node_modules/@storybook/angular/dist/client/preview/render.js
 @ ./node_modules/@storybook/angular/dist/client/preview/index.js
 @ ./node_modules/@storybook/angular/dist/client/index.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/angular/dist/server/config/polyfills.js ./node_modules/@storybook/angular/dist/server/config/globals.js (webpack)-hot-middleware/client.js?reload=true ./.storybook/config.js

ERROR in ./node_modules/@storybook/angular/dist/client/preview/angular/components/app.component.ts
Module build failed: Error: Typescript emitted no output for /home/user/projects/tests/sb/node_modules/@storybook/angular/dist/client/preview/angular/components/app.component.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader (/home/user/projects/tests/sb/node_modules/ts-loader/dist/index.js:47:15)
    at Object.loader (/home/user/projects/tests/sb/node_modules/ts-loader/dist/index.js:29:12)
 @ ./node_modules/@storybook/angular/dist/client/preview/angular/helpers.ts 7:22-59
 @ ./node_modules/@storybook/angular/dist/client/preview/render.js
 @ ./node_modules/@storybook/angular/dist/client/preview/index.js
 @ ./node_modules/@storybook/angular/dist/client/index.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/angular/dist/server/config/polyfills.js ./node_modules/@storybook/angular/dist/server/config/globals.js (webpack)-hot-middleware/client.js?reload=true ./.storybook/config.js

ERROR in ./node_modules/@storybook/angular/dist/client/preview/angular/components/error.component.ts
Module build failed: Error: Typescript emitted no output for /home/user/projects/tests/sb/node_modules/@storybook/angular/dist/client/preview/angular/components/error.component.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader (/home/user/projects/tests/sb/node_modules/ts-loader/dist/index.js:47:15)
    at Object.loader (/home/user/projects/tests/sb/node_modules/ts-loader/dist/index.js:29:12)
 @ ./node_modules/@storybook/angular/dist/client/preview/angular/helpers.ts 8:24-63
 @ ./node_modules/@storybook/angular/dist/client/preview/render.js
 @ ./node_modules/@storybook/angular/dist/client/preview/index.js
 @ ./node_modules/@storybook/angular/dist/client/index.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/angular/dist/server/config/polyfills.js ./node_modules/@storybook/angular/dist/server/config/globals.js (webpack)-hot-middleware/client.js?reload=true ./.storybook/config.js

ERROR in ./node_modules/@storybook/angular/dist/client/preview/angular/components/no-preview.component.ts
Module build failed: Error: Typescript emitted no output for /home/user/projects/tests/sb/node_modules/@storybook/angular/dist/client/preview/angular/components/no-preview.component.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader (/home/user/projects/tests/sb/node_modules/ts-loader/dist/index.js:47:15)
    at Object.loader (/home/user/projects/tests/sb/node_modules/ts-loader/dist/index.js:29:12)
 @ ./node_modules/@storybook/angular/dist/client/preview/angular/helpers.ts 9:29-73
 @ ./node_modules/@storybook/angular/dist/client/preview/render.js
 @ ./node_modules/@storybook/angular/dist/client/preview/index.js
 @ ./node_modules/@storybook/angular/dist/client/index.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/angular/dist/server/config/polyfills.js ./node_modules/@storybook/angular/dist/server/config/globals.js (webpack)-hot-middleware/client.js?reload=true ./.storybook/config.js

ERROR in ./node_modules/@storybook/angular/dist/client/preview/angular/utils.ts
Module build failed: Error: Typescript emitted no output for /home/user/projects/tests/sb/node_modules/@storybook/angular/dist/client/preview/angular/utils.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader (/home/user/projects/tests/sb/node_modules/ts-loader/dist/index.js:47:15)
    at Object.loader (/home/user/projects/tests/sb/node_modules/ts-loader/dist/index.js:29:12)
 @ ./node_modules/@storybook/angular/dist/client/preview/angular/helpers.ts 11:14-32
 @ ./node_modules/@storybook/angular/dist/client/preview/render.js
 @ ./node_modules/@storybook/angular/dist/client/preview/index.js
 @ ./node_modules/@storybook/angular/dist/client/index.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/angular/dist/server/config/polyfills.js ./node_modules/@storybook/angular/dist/server/config/globals.js (webpack)-hot-middleware/client.js?reload=true ./.storybook/config.js
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks  Chunk Names
    index.html  569 kB       0  
       [0] ./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/angular/dist/server/index.html.ejs 1.69 kB {0} [built]
       [1] ./node_modules/lodash/lodash.js 540 kB {0} [built]
       [2] (webpack)/buildin/global.js 488 bytes {0} [built]
       [3] (webpack)/buildin/module.js 495 bytes {0} [built]
Child html-webpack-plugin for "iframe.html":
          Asset    Size  Chunks  Chunk Names
    iframe.html  568 kB       0  
       [0] ./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/angular/dist/server/iframe.html.ejs 974 bytes {0} [built]
       [1] ./node_modules/lodash/lodash.js 540 kB {0} [built]
       [2] (webpack)/buildin/global.js 488 bytes {0} [built]
       [3] (webpack)/buildin/module.js 495 bytes {0} [built]


```
### Steps to reproduce

```
ng new sb --skip-install
change typescript version to 2.6.1 in package.json
getstorybook
npm run storybook
```

storybook/angular ^3.4.0-alpha.1

**Comment by alterx** [comment]
Hey, @user753 , which Angular version are you using? 
Support for TypeScript 2.6 came out *yesterday* for Angular (https://blog.angular.io/angular-5-2-now-available-312d1099bd81).

**Comment by user753** [comment]
@alterx 5.2
I run this today
```
ng new sb --skip-install
change typescript version to 2.6.1 in package.json
getstorybook
npm run storybook
```

**Comment by Quramy** [comment]
I think It is premature to use TypeScript 2.6 because there is some issues related with Angular5.2 and TS 2.6

- https://github.com/angular/angular/issues/21466
- https://github.com/angular/angular/issues/21591

Even [the angular team reverted back to TS 2.5.x](https://github.com/angular/devkit/commit/653bb81eb60a3c013750e01f416a4e78182fde5f) .

**Comment by alterx** [comment]
Yeah, there are also issues related to how we distribute the app (well have to look into compiling our .ts files instead of distributing them as-is) but, for the time being, I do think it is premature to use TS 2.6

**Comment by michaelgeorgeattard** [comment]
I think providing `.js` + `.d.ts` files, as @alterx mentioned, would be ideal.

We are currently using Typescript `~2.6.1` with Angular `^5.2.0` in multiple libraries, and not being able to build `storybook` is a bit of a blocker for now.

**Comment by alterx** [comment]
Yeah, that's the way to go. But I honestly don't know the full extent of doing it with our current monorepo setup so can't really compromise to a release date on this as it would involve other members of the team. Are you using any specific TS 2.6 feature? I mean, Angular just enabled support and even they went back to a previous version for a bit.

**Comment by michaelgeorgeattard** [comment]
In most libraries TS was upgraded mostly to be on the latest and greatest. Looking at the `2.6` changelog I don't think we are using the new features anywhere.

However on some specific libraries we might need to upgrade to `next` (`2.7`) as latest Angular is complaining under very specific circumstances when TS is `< 2.7`.

For now we are setting up `storybook` and trying out some use cases. When we're done we'll decide whether to downgrade TS, however ideally at that stage latest version is supported.

**Comment by alterx** [comment]
@michaelgeorgeattard, with https://github.com/storybooks/storybook/pull/2846 these errors should be gone. This one just got merged and will probably be included in this week's alpha release

**Comment by alexandru-tomescu** [comment]
I have the same problem @alterx . Did you already solve the problem ? Thanks !

**Comment by alterx** [comment]
@alexandru-tomescu , as I mentioned in the comment, this one will probably be included in this week's alpha release.

**Comment by alterx** [comment]
Also, I'm curious, @michaelgeorgeattard, which are these "very specific circumstances" in which Angular is complaining if TS version is under 2.7.
As far as I know, TS 2.7 was released just [yesterday](https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/) and it seems pretty weird that Angular (that just released [support for 2.6 ](https://blog.angular.io/angular-5-2-now-available-312d1099bd81)) would complain about the TS version being < 2.7 
Are you guys using 6.0.0 beta or something like that? 🤔

**Comment by alexandru-tomescu** [comment]
I switched to TS@2.5.3 (latest 2.5.x version) and now there are no more errors.

**Comment by michaelgeorgeattard** [comment]
@alterx 

Issue was emerging when trying to do an AOT build with a function being passed as a decorator parameter, something like below:

```ts
@foo(() => 5)
bar() {
}
```

Technical details: https://github.com/Microsoft/TypeScript/issues/17384

**Comment by alterx** [comment]
@alexandru-tomescu, well, the alpha hasn't been released yet and this issue was specific to TS 2.6, which versions of TS, Angular and Storybook you had before?

@michaelgeorgeattard I see, yeah. Hopefully now that we're compiling the .ts files this issue will go away and you'll be able to use TS 2.7

I'll keep you guys posted on this alpha so you can test :)

**Comment by alexandru-tomescu** [comment]
@alterx I just started a fresh Angular project. I didn't use TS before because i was using ReactJS.

**Comment by alterx** [comment]
[Alpha 7](https://github.com/storybooks/storybook/releases/tag/v3.4.0-alpha.7) is out and we're now distributing compiled ts files :)
Please test and let us know how it goes.

**Comment by michaelgeorgeattard** [comment]
@alterx https://github.com/storybooks/storybook/releases/tag/v3.4.0-alpha.7 worked fine with Typescript 2.7. Thanks :-)

**Comment by alterx** [comment]
Perfect @michaelgeorgeattard 😄 
@user753 , is this also working for you?

**Comment by user753** [comment]
@alterx it seems to work fine

**Comment by sanyashvets** [comment]
still getting same errors with 2.7, 2.8 TS versions
