### ISSUE TITLE
TypeError: [BABEL] /project1/.storybook/config.js: Invalid options type for foreign

### ISSUE THREAD

**Issue by rjbergerud** [storybooks/storybook#2810]
### Issue details
I'm trying to add storybook to an existing project.
Following storybook for React guide (slowstart) gives the following error.  The same happens when I use the @storybook/cli.

### Please specify which version of Storybook and optionally any affected addons that you're running

- storybook/react 5.5.1
- storybook/cli 5.5.1

```
ERROR in ./.storybook/config.js
Module build failed: TypeError: [BABEL](/media/ryder/4b16cf63-5c01-4664-9954-fbb9dbaba9d1/sukow/inkfrog-app/.storybook/config.js: Invalid options type for foreign
    at Logger.error (/media/ryder/4b16cf63-5c01-4664-9954-fbb9dbaba9d1/sukow/inkfrog-app/node_modules/babel-core/lib/transformation/file/logger.js:43:11)
    at OptionManager.mergeOptions (/media/ryder/4b16cf63-5c01-4664-9954-fbb9dbaba9d1/sukow/inkfrog-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:245:16)
    at OptionManager.mergePresets (/media/ryder/4b16cf63-5c01-4664-9954-fbb9dbaba9d1/sukow/inkfrog-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:332:14)
    at OptionManager.mergeOptions (/media/ryder/4b16cf63-5c01-4664-9954-fbb9dbaba9d1/sukow/inkfrog-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:289:12)
    at OptionManager.init (/media/ryder/4b16cf63-5c01-4664-9954-fbb9dbaba9d1/sukow/inkfrog-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:414:10)
    at File.initOptions (/media/ryder/4b16cf63-5c01-4664-9954-fbb9dbaba9d1/sukow/inkfrog-app/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/media/ryder/4b16cf63-5c01-4664-9954-fbb9dbaba9d1/sukow/inkfrog-app/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/media/ryder/4b16cf63-5c01-4664-9954-fbb9dbaba9d1/sukow/inkfrog-app/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at transpile (/media/ryder/4b16cf63-5c01-4664-9954-fbb9dbaba9d1/sukow/inkfrog-app/node_modules/@storybook/react/node_modules/babel-loader/lib/index.js:50:20)
    at /media/ryder/4b16cf63-5c01-4664-9954-fbb9dbaba9d1/sukow/inkfrog-app/node_modules/@storybook/react/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/media/ryder/4b16cf63-5c01-4664-9954-fbb9dbaba9d1/sukow/inkfrog-app/node_modules/@storybook/react/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js (webpack)-hot-middleware/client.js?reload=true ./.storybook/config.js
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks  Chunk Names
    index.html  569 kB       0  
       [0] ./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/react/dist/server/index.html.ejs 1.69 kB {0} [built]
       [1] ./node_modules/lodash/lodash.js 540 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
Child html-webpack-plugin for "iframe.html":
          Asset    Size  Chunks  Chunk Names
    iframe.html  568 kB       0  
       [0] ./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/react/dist/server/iframe.html.ejs 966 bytes {0} [built]
       [1] ./node_modules/lodash/lodash.js 540 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
```

### Steps to reproduce

The only thing that I've followed differently from the guide is to keep stories folder in `/src/stories`.

The relevant fields in package.json are 
```
"dependencies": {
    "axios": "^0.12.0",
    "basscss": "^8.0.1",
    "braintree-web-drop-in": "^1.6.1",
    "env-cmd": "^5.0.0",
    "es6-promise": "^4.1.1",
    "postcss-loader": "^0.9.1",
    "react": "^15.0.2",
    "react-async-component": "^1.0.0-beta.3",
    "react-bootstrap": "^0.29.3",
    "react-country-region-selector": "^1.1.0",
    "react-credit-cards": "^0.4.1",
    "react-css-modules": "^4.1.0",
    "react-dom": "^15.0.2",
    "react-intl": "^2.2.3",
    "react-redux": "^5.0.4",
    "react-router": "^4.1.1",
    "react-router-dom": "^4.1.1",
    "react-stripe-checkout": "^2.4.0",
    "react-tap-event-plugin": "^2.0.0",
    "redux": "^3.6.0",
    "whatwg-fetch": "^1.0.0"
  },
  "devDependencies": {
    "@kadira/storybook": "^2.21.0",
    "@kwltrs/tape-jsx-assertions": "0.0.1",
    "@storybook/react": "^3.3.10",
    "autoprefixer": "^6.7.7",
    "babel-cli": "^6.24.1",
    "babel-core": "^6.1.21",
    "babel-eslint": "4.1.x",
    "babel-loader": "6.1.x",
    "babel-preset-es2015": "6.1.x",
    "babel-preset-react": "^6.1.18",
    "babel-preset-stage-0": "6.22.x",
    "babel-register": "6.1.x",
    "babel-tape-runner": "2.0.x",
    "bundle-loader": "^0.5.5",
    "css-loader": "^0.28.4",
    "env-cmd": "^5.0.0",
    "enzyme": "2.3.0",
    "exports-loader": "0.6.2",
    "extend-tape": "1.2.0",
    "extract-text-webpack-plugin": "2.1.x",
    "file-loader": "^0.8.5",
    "gulp": "3.9.0",
    "html-webpack-plugin": "^2.30.1",
    "imports-loader": "0.6.5",
    "jsdom": "9.2.1",
    "json-loader": "0.5.4",
    "leaked-handles": "5.2.0",
    "memory-fs": "0.3.0",
    "node-sass": "4.5.0",
    "optimize-css-assets-webpack-plugin": "^1.3.0",
    "postcss": "5.0.14",
    "postcss-cssnext": "2.4.0",
    "postcss-import": "8.1.0",
    "postcss-loader": "0.9.1",
    "postcss-nested-vars": "0.0.2",
    "postcss-url": "5.1.0",
    "precss": "1.4.0",
    "react": "^15.0.2",
    "react-addons-test-utils": "15.1.0",
    "react-component-gulp-tasks": "0.7.6",
    "react-dom": "0.14.0",
    "react-hot-loader": "3.0.0-beta.6",
    "resolve-url-loader": "2.0.2",
    "sass-loader": "6.0.2",
    "static-site-generator-webpack-plugin": "3.3.0",
    "style-loader": "0.13.0",
    "tape": "4.6.0",
    "to-string-loader": "^1.1.5",
    "transform-loader": "0.2.3",
    "url-loader": "0.5.7",
    "webpack": "2.x.x",
    "webpack-dev-middleware": "1.10.x",
    "webpack-dev-server": "2.4.x",
    "webpack-hot-middleware": "2.17.x"
  },
  "peerDependencies": {
    "react": "^15.0.2"
  },
  "browserify-shim": {
    "react": "global:React"
  },
  "scripts": {
    "build": "webpack",
    "lint": "eslint ./; true",
    "start": "NODE_ENV=development node_modules/.bin/webpack-dev-server",
    "test": "echo \"no tests yet\" && exit 0",
    "storybook": "start-storybook -p  6006 -c .storybook",
    "build-storybook": "build-storybook"
  },
  "keywords": [
    "inkfrog",
    "shopping",
    "tracking"
  ]
}
```

**Comment by igor-dv** [comment]
What is the version of babel-core is actually installed to the node_modeuls?
storybook has a peer of "^6.26.0 || ^7.0.0-0".

**Comment by rjbergerud** [comment]
Upgrading it to 6.26.0 fixed this issue.  Thanks!
