### ISSUE TITLE
Can't use react-modal with Storybook Storyshots

### ISSUE THREAD

**Issue by javidjamae** [storybooks/storybook#2822]
### Issue details

I'm using Storybook and running tests with Jest / Storyshots.

When I use a component that references a modal, I get the following error when running my tests:

```
    TypeError: Cannot read property 'appendChild' of null

      at Modal.componentDidMount (node_modules/react-modal/lib/components/Modal.js:93:13)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4553:24)
      at commitAllLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5729:9)
      at HTMLUnknownElement.callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1610:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:219:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:126:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:36:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:61:35)
      at Object.invokeGuardedCallbackDev (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1649:16)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1506:29)
      at commitRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5833:9)
      at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6800:42)
      at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6750:7)
      at requestWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6661:7)
      at scheduleWorkImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6515:11)
      at scheduleWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6472:12)
      at scheduleTopLevelUpdate (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6976:5)
      at Object.updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7014:7)
      at create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7637:18)
      at getRenderedTree (node_modules/@storybook/addon-storyshots/dist/test-bodies.js:36:14)
      at Object.test (node_modules/@storybook/addon-storyshots/dist/test-bodies.js:46:16)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/index.js:174:28)
          at Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

Based on [this code](https://github.com/storybooks/storybook/blob/master/lib/ui/src/modules/ui/components/search_box.stories.js#L17-L19) in the Storybook project, it appears that a similar issue has been encountered and that the workaround was to just skip those tests. (That code was modified by @tmeasday and @ndelangen so maybe they have some insights here?) 

Unfortunately, the component that I have that is using a modal is part of my header (I'm using it for a popup menu). That means that I would have to ignore a large number of my screen tests, which I'd prefer not to do.

I'm assuming the problem is that when the test is running, there is not document / body specified. Is there a workaround here? Should I just avoid using react-modal and find another library to do my popup menu in the header?

### Steps to reproduce

1) Create a component that uses a react-modal `Modal`:

```
      <Modal
        appElement={ document.body }
        isOpen={ modalActive }
        onRequestClose={ onClick }
        parentSelector={ () => document.querySelector( '.SettingsLink' ) }
        style={ modalStyles }
      >
        ...
      </Modal>
```

2) Run a storybook test

### Please specify which version of Storybook and optionally any affected addons that you're running
```
  "@babel/core": "^7.0.0-beta.37",
    "@babel/preset-react": "^7.0.0-beta.37",
    "@storybook/addon-actions": "^3.3.3",
    "@storybook/addon-links": "^3.3.3",
    "@storybook/addon-storyshots": "^3.3.8",
    "@storybook/react": "^3.3.3",
    "@types/googlemaps": "^3.30.3",
    "@types/markerclustererplus": "^2.1.33",
    "@types/react": "^16.0.0",
    "babel-jest": "^22.0.4",
    "enzyme": "^3.2.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "enzyme-to-json": "^3.3.0",
    "jest": "^21.2.1",
    "jest-enzyme": "^4.0.1",
    "react-test-renderer": "^16.0.0",
    "redux-mock-store": "^1.4.0",
    "redux-test-utils": "^0.2.2",
    "sinon": "^3.1.0",
    "storybook-router": "^0.3.2"
```

**Comment by ndelangen** [comment]
Thanks for this thorough and detailed bug report @javidjamae 

It seems `react-modal` needs real DOM apis to function, which are not available in Jest & jsdom.
I do not have an immediate solution for you.

Perhaps the DOM apis can be mocked?

**Comment by javidjamae** [comment]
Thanks for the quick reply @ndelangen! I ended up switching to [react-simple-dropdown](https://github.com/Fauntleroy/react-simple-dropdown) for my menu instead, which didn't pose any of the DOM issues. But, I kept a branch around to test out any possible solutions that might pop up on here in case anybody else wants to know what the outcome was.

**Comment by at0g** [comment]
I got around this by replacing react-modal:

```js
// file: jest.config.js
moduleNameMapper: {
'react-modal': '<rootDir>/src/__mocks__/emptyComponent.js',
}
```

```js
// file: src/__mocks__/emptyComponent.js
import React from 'react';

export default Object.assign(
    ({ children, ...props }) => (
        <div>
            <code><pre>{JSON.stringify(props, null, 4)}</pre></code>
            {children}
        </div>
    ),
    {
        displayName: 'EmptyComponentMock',
    },
);
```

**Comment by mlabrum** [comment]
This also works:
Add the following to your `Storyshots.test.js` file
```js
jest.mock("react-modal", () => {
	return function Modal(props){
		return props.isOpen ? props.children : null
	}
})
```

**Comment by danielduan** [comment]
I'm going to close this because this is an issue with `react-modal` and jest in general and not with Storybook.

**Comment by justin-barca-at-camis** [comment]
For the sake of documentation, I'd like to challenge what @danielduan said about this being an issue with jest and not storybook/storyshot. I was able to run a jest snapshot test for a component that uses the DOM api (react-modern-calendar-datepicker) but I couldn't run a storyshots test for that same component using the same props.
