### ISSUE TITLE
Angular + Knobs throws error

### ISSUE THREAD

**Issue by amcdnl** [storybooks/storybook#2899]
## Issue
When defining a bare bones story and using knobs in your project at the top level, you will receive this error.

**timeline.stories.ts**
```javascript
import { storiesOf } from '@storybook/angular';

storiesOf('Timeline', module)
    .add('Basic', () => ({
        templates: `
        <ul class="flow-list">
            <li>
                Blah
            </li>
        </ul>
        `,
        moduleMetadata: {
            imports: []
        }
    }));

```

**.storybook/config.js**
```javascript
import { configure, addDecorator } from '@storybook/angular';
import { withKnobs } from '@storybook/addon-knobs/angular';

addDecorator(withKnobs);

const req = require.context('../src/stories', true, /index|.stories\.ts$/);
function loadStories() {
  req.keys().forEach((filename) => req(filename));
}

configure(loadStories, module);
```

Throws this error:

```
preview.bundle.js:124288 Unhandled Promise rejection: No template specified for component KnobWrapperComponent ; Zone: <root> ; Task: Promise.then ; Value: Error: No template specified for component KnobWrapperComponent
    at syntaxError (preview.bundle.js:172614)
    at DirectiveNormalizer.normalizeTemplate (preview.bundle.js:175301)
    at CompileMetadataResolver.loadDirectiveMetadata (preview.bundle.js:187036)
    at preview.bundle.js:206540
    at Array.forEach (<anonymous>)
    at preview.bundle.js:206539
    at Array.forEach (<anonymous>)
    at JitCompiler._loadModules (preview.bundle.js:206536)
    at JitCompiler._compileModuleAndComponents (preview.bundle.js:206494)
    at JitCompiler.compileModuleAsync (preview.bundle.js:206388) Error: No template specified for component KnobWrapperComponent
    at syntaxError (http://localhost:6006/static/preview.bundle.js:172614:34)
    at DirectiveNormalizer.normalizeTemplate (http://localhost:6006/static/preview.bundle.js:175301:19)
    at CompileMetadataResolver.loadDirectiveMetadata (http://localhost:6006/static/preview.bundle.js:187036:75)
    at http://localhost:6006/static/preview.bundle.js:206540:72
    at Array.forEach (<anonymous>)
    at http://localhost:6006/static/preview.bundle.js:206539:72
    at Array.forEach (<anonymous>)
    at JitCompiler._loadModules (http://localhost:6006/static/preview.bundle.js:206536:75)
    at JitCompiler._compileModuleAndComponents (http://localhost:6006/static/preview.bundle.js:206494:36)
    at JitCompiler.compileModuleAsync (http://localhost:6006/static/preview.bundle.js:206388:37)
```

**Comment by amcdnl** [comment]
Ugh, typo in `templates`. Closing but should probably have better error messages.
