### ISSUE TITLE
Can not run @storybook/angular after installation

### ISSUE THREAD

**Issue by Kamilius** [storybooks/storybook#2981]
### Issue details

Expected: to see page with component and without any errors, at least some meaningful errors.
Actual: got following errors in terminal for Webpack (`npm run storybook`) and same duplicated in `localhost:9001` page's content area (`#storybook-preview-iframe`):

```
ERROR in ./node_modules/@storybook/angular/dist/client/preview/angular/app.token.ts
Module build failed: Error: Typescript emitted no output for /myProj/node_modules/@storybook/angular/dist/client/preview/angular/app.token.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader (/myProj/node_modules/@storybook/angular/node_modules/ts-loader/dist/index.js:47:15)
    at Object.loader (/myProj/node_modules/@storybook/angular/node_modules/ts-loader/dist/index.js:29:12)
 @ ./node_modules/@storybook/angular/dist/client/preview/angular/helpers.ts 10:18-40
 @ ./node_modules/@storybook/angular/dist/client/preview/render.js
 @ ./node_modules/@storybook/angular/dist/client/preview/index.js
 @ ./node_modules/@storybook/angular/dist/client/index.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/angular/dist/server/config/polyfills.js ./node_modules/@storybook/angular/dist/server/config/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js

ERROR in ./node_modules/@storybook/angular/dist/client/preview/angular/components/app.component.ts
Module build failed: Error: Typescript emitted no output for /myProj/node_modules/@storybook/angular/dist/client/preview/angular/components/app.component.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader (/myProj/node_modules/@storybook/angular/node_modules/ts-loader/dist/index.js:47:15)
    at Object.loader (/myProj/node_modules/@storybook/angular/node_modules/ts-loader/dist/index.js:29:12)
 @ ./node_modules/@storybook/angular/dist/client/preview/angular/helpers.ts 7:22-59
 @ ./node_modules/@storybook/angular/dist/client/preview/render.js
 @ ./node_modules/@storybook/angular/dist/client/preview/index.js
 @ ./node_modules/@storybook/angular/dist/client/index.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/angular/dist/server/config/polyfills.js ./node_modules/@storybook/angular/dist/server/config/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js

ERROR in ./node_modules/@storybook/angular/dist/client/preview/angular/components/error.component.ts
Module build failed: Error: Typescript emitted no output for /myProj/node_modules/@storybook/angular/dist/client/preview/angular/components/error.component.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader (/myProj/node_modules/@storybook/angular/node_modules/ts-loader/dist/index.js:47:15)
    at Object.loader (/myProj/node_modules/@storybook/angular/node_modules/ts-loader/dist/index.js:29:12)
 @ ./node_modules/@storybook/angular/dist/client/preview/angular/helpers.ts 8:24-63
 @ ./node_modules/@storybook/angular/dist/client/preview/render.js
 @ ./node_modules/@storybook/angular/dist/client/preview/index.js
 @ ./node_modules/@storybook/angular/dist/client/index.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/angular/dist/server/config/polyfills.js ./node_modules/@storybook/angular/dist/server/config/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js

ERROR in ./node_modules/@storybook/angular/dist/client/preview/angular/components/no-preview.component.ts
Module build failed: Error: Typescript emitted no output for /myProj/node_modules/@storybook/angular/dist/client/preview/angular/components/no-preview.component.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader (/myProj/node_modules/@storybook/angular/node_modules/ts-loader/dist/index.js:47:15)
    at Object.loader (/myProj/node_modules/@storybook/angular/node_modules/ts-loader/dist/index.js:29:12)
 @ ./node_modules/@storybook/angular/dist/client/preview/angular/helpers.ts 9:29-73
 @ ./node_modules/@storybook/angular/dist/client/preview/render.js
 @ ./node_modules/@storybook/angular/dist/client/preview/index.js
 @ ./node_modules/@storybook/angular/dist/client/index.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/angular/dist/server/config/polyfills.js ./node_modules/@storybook/angular/dist/server/config/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js

ERROR in ./node_modules/@storybook/angular/dist/client/preview/angular/utils.ts
Module build failed: Error: Typescript emitted no output for /myProj/node_modules/@storybook/angular/dist/client/preview/angular/utils.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader (/myProj/node_modules/@storybook/angular/node_modules/ts-loader/dist/index.js:47:15)
    at Object.loader (/myProj/node_modules/@storybook/angular/node_modules/ts-loader/dist/index.js:29:12)
 @ ./node_modules/@storybook/angular/dist/client/preview/angular/helpers.ts 11:14-32
 @ ./node_modules/@storybook/angular/dist/client/preview/render.js
 @ ./node_modules/@storybook/angular/dist/client/preview/index.js
 @ ./node_modules/@storybook/angular/dist/client/index.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/angular/dist/server/config/polyfills.js ./node_modules/@storybook/angular/dist/server/config/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js
```

### Steps to reproduce

1. Add `@storybook/angular` on top of `https://github.com/robisim74/angular-library-starter` library.
2. Follow `Starter guide for Angular` https://storybook.js.org/basics/guide-angular/ up to step `Run your storybook`.
3. Run storybook and check terminal, or open `localhost:9001` in your browser to see errors.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/angular 3.3.13
- babel-core 6.26.0

Also a `tsconfig.json` it is taking is a config from project's root. This config has `strict: true` which also caused a lot of issues during build. After turning this `strict mode` off, only errors described above left.

**Comment by igor-dv** [comment]
@Kamilius , can you please try the v3.4.0-alpha.8? We are distributing our ts files there.

**Comment by Kamilius** [comment]
sure, `@storybook/angular@3.4.0-alpha.8`?

**Comment by igor-dv** [comment]
Yeah. Actually, change every `@strobook/*` dep you have

**Comment by Kamilius** [comment]
@igor-dv thanks, it worked.
