### ISSUE TITLE
Cannot read property 'close' of undefined

### ISSUE THREAD

**Issue by bannier** [storybooks/storybook#3222]
### Issue details

When running storyshots I get this error

```
      TypeError: Cannot read property 'close' of undefined

      1 | /* eslint-env jest */
      2 | 
    > 3 | import initStoryshots from '@storybook/addon-storyshots';
      4 | 
      5 | require('./storyshotsMocks.js');
      6 | 
      
      at Object.<anonymous> (node_modules/chalk/index.js:72:74)
      at Object.<anonymous> (node_modules/jest-specific-snapshot/dist/index.js:12:21)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/test-bodies.js:29:1)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/index.js:18:19)
```
### Steps to reproduce

Run test including storyshots

### Please specify which version of Storybook and optionally any affected addons that you're running

- storybook/react 3.3.15
- storybook/addon-storyshots 3.3.15

**Comment by igor-dv** [comment]
Duplicate: https://github.com/igor-dv/jest-specific-snapshot/issues/8
