### ISSUE TITLE
[addon-storyshots] unable to run tests. Transforming files is not supported in browsers

### ISSUE THREAD

**Issue by kamthamc** [storybooks/storybook#3503]
### Bug or support request summary
Upgrading `@babel/core` to `7.0.0-beta.46` breaking snapshot testing (storybook is working in browser). May be babel 7 no longer su.

```
    Transforming files is not supported in browsers

      2 | import 'jest-styled-components';
      3 |
    > 4 | initStoryshots();
        | ^
      5 |

      at Object.transformFileSync (node_modules/@babel/core/lib/transform-file-sync-browser.js:9:9)
      at getConfigContent (node_modules/@storybook/addon-storyshots/dist/config-loader.js:24:16)
      at load (node_modules/@storybook/addon-storyshots/dist/config-loader.js:34:17)
      at Object.load (node_modules/@storybook/addon-storyshots/dist/react/loader.js:26:48)
      at loadFramework (node_modules/@storybook/addon-storyshots/dist/frameworkLoader.js:36:17)
      at testStorySnapshots (node_modules/@storybook/addon-storyshots/dist/index.js:68:54)
      at Object.<anonymous> (stories/SnapshotStoryTest.js:4:1)
```

### Steps to reproduce
N/A
### Please specify which version of Storybook and optionally any affected addons that you're running

- storybook/react  - 4.0.0-alpha.4, 3.4.3
- storybook/addon-storyshots  - 4.0.0-alpha.4, 3.4.3

### Affected platforms 
- babel/core > 7

### Screenshots / Screencast / Code Snippets (Optional)

```js
import initStoryshots from '@storybook/addon-storyshots';
import 'jest-styled-components';

initStoryshots();
```

**Comment by kamthamc** [comment]
this works when the browser is set to false with babel-core@7
