### ISSUE TITLE
Unable to make postcss work with alias and typescript

### ISSUE THREAD

**Issue by alveshelio** [storybooks/storybook#3601]
Hi guys,

I'm having a hard making storybook work fine with my set up.

I've created an app with create-react-app with Typescript scripts.
I've ejected my app and I've added css modules, here's my `webpack.config.dev.js` in `config/webpack.config.dev.js`

```
'use strict';

const autoprefixer = require('autoprefixer');
const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CaseSensitivePathsPlugin = require('case-sensitive-paths-webpack-plugin');
const InterpolateHtmlPlugin = require('react-dev-utils/InterpolateHtmlPlugin');
const WatchMissingNodeModulesPlugin = require('react-dev-utils/WatchMissingNodeModulesPlugin');
const ModuleScopePlugin = require('react-dev-utils/ModuleScopePlugin');
const getClientEnvironment = require('./env');
const paths = require('./paths');
const pkg = require('../package.json');
function srcPath(subdir) {
	return path.join(__dirname, '../src', subdir);
}

const publicPath = '/';
const publicUrl = '';
const env = getClientEnvironment(publicUrl);

module.exports = {
	devtool: 'cheap-module-source-map',
	cache: true,
	entry: [
		require.resolve('./polyfills'),
		paths.appIndexJs,
	],
	output: {
		path: paths.appBuild,
		pathinfo: true,
		filename: 'static/js/bundle.js',
		chunkFilename: 'static/js/[name].chunk.js',
		publicPath: publicPath,
		devtoolModuleFilenameTemplate: info =>
			path.resolve(info.absoluteResourcePath).replace(/\\/g, '/'),
	},
	resolve: {
		modules: ['node_modules', paths.appNodeModules].concat(
			process.env.NODE_PATH.split(path.delimiter).filter(Boolean),
		),
		extensions: [
			'.web.ts',
			'.ts',
			'.web.tsx',
			'.tsx',
			'.web.js',
			'.js',
			'.json',
			'.web.jsx',
			'.jsx',
		],
		alias: {
			actions: srcPath('store/actions'),
			api: srcPath('api'),
			data: srcPath('data'),
			reducers: srcPath('store/reducers'),
			components: srcPath('components'),
			containers: srcPath('containers'),
			instances: srcPath('instances'),
			i18n: srcPath('i18n'),
			shared: srcPath('shared'),
			models: srcPath('models'),
			config: srcPath('config'),
			'react-native': 'react-native-web',
		},
		plugins: [	
			new ModuleScopePlugin(paths.appSrc, [paths.appPackageJson]),
		],
	},
	module: {
		loaders: [{ include: /\.json$/, loaders: ['json-loader'] }],
		strictExportPresence: true,
		rules: [		
			{
				test: /\.(ts|tsx)$/,
				loader: require.resolve('tslint-loader'),
				enforce: 'pre',
				include: paths.appSrc,
			},
			{
				test: /\.js$/,
				loader: require.resolve('source-map-loader'),
				enforce: 'pre',
				include: paths.appSrc,
			},
			{
				oneOf: [
					{
						test: [/\.bmp$/, /\.gif$/, /\.jpe?g$/, /\.png$/],
						loader: require.resolve('url-loader'),
						options: {
							limit: 10000,
							name: 'static/media/[name].[hash:8].[ext]',
						},
					},
					{
						test: /\.(ts|tsx)$/,
						include: paths.appSrc,
						loader: 'awesome-typescript-loader',
						options: {
							useCache: true,
							forceIsolatedModules: true,
							reportFiles: ['src/**/*.{ts,tsx}'],
						},
					},
					{
						test: /\.css$/,
						use: [
							require.resolve('style-loader'),
							{
								loader: require.resolve('css-loader'),
								options: {
									importLoaders: 1,
									modules: true,
									localIdentName: '[name]__[local]__[hash:base64:5]',
								},
							},
							{
								loader: require.resolve('postcss-loader'),
								options: {
									ident: 'postcss',
									plugins: () => [
										require('postcss-flexbugs-fixes'),
										autoprefixer({
											browsers: [
												'>1%',
												'last 4 versions',
												'Firefox ESR',
												'not ie < 9', // React doesn't support IE8 anyway
											],
											flexbox: 'no-2009',
										}),
									],
								},
							},
						],
						exclude: /node_modules/,
					},
					{
						test: /\.css$/,
						include: /node_modules/,
						use: ['style-loader', 'css-loader'],
					},
					{
						exclude: [/\.js$/, /\.html$/, /\.json$/],
						loader: require.resolve('file-loader'),
						options: {
							name: 'static/media/[name].[hash:8].[ext]',
						},
					},
				],
			},
		],
	},
	plugins: [
		new InterpolateHtmlPlugin(env.raw),
		new HtmlWebpackPlugin({
			files: {
				js: '/config/config.js',
			},
			scripts: ['/config/config.js'],
			inject: true,
			title: 'EMP2',
			template: paths.appHtml,
		}),
		new webpack.NamedModulesPlugin(),
		new webpack.DefinePlugin(env.stringified),
		new webpack.HotModuleReplacementPlugin(),
		new CaseSensitivePathsPlugin(),
		new WatchMissingNodeModulesPlugin(paths.appNodeModules),
		new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
		new webpack.DefinePlugin({
			'process.env': {
				version: JSON.stringify(pkg.version),
				build: JSON.stringify(pkg['build.number']),
			},
		}),
	],
	node: {
		dgram: 'empty',
		fs: 'empty',
		net: 'empty',
		tls: 'empty',
		child_process: 'empty',
	},
	performance: {
		hints: false,
	},
};

```

I have this structure
```
myProject
  --.storybook
  --config (create-react-app configuration files)
  --public
  --scripts (create-react-app script files)
  --src
    --api
    --components
    --containers
    --data
    --i18n
    --instances
    --models
    --shared
    --store
        --actions
        --reducers
        -- etc. etc etc
  --stories
```

And heres' my `webpack.config.js` in `.storybook/`

```
const path = require("path");
const SRC_PATH = path.join(__dirname, "../src");

module.exports = {
	resolve: {
		alias: {
			actions: path.resolve(__dirname, "../src/store/actions"),
			api: path.resolve(__dirname, "../src/api"),
			data: path.resolve(__dirname, "../src/data"),
			reducers: path.resolve(__dirname, "../src/reducers"),
			components: path.resolve(__dirname, "../src/components"),
			containers: path.resolve(__dirname, "../src/containers"),
			instances: path.resolve(__dirname, "../src/instances"),
			i18n: path.resolve(__dirname, "../src/i18n"),
			shared: path.resolve(__dirname, "../src/shared"),
			models: path.resolve(__dirname, "../src/models"),
			config: path.resolve(__dirname, "../src/config"),
		},
		extensions: [
			'.web.ts',
			'.ts',
			'.web.tsx',
			'.tsx',
			'.web.js',
			'.js',
			'.json',
			'.web.jsx',
			'.jsx',
		],
	},
	module: {
		rules: [
			{
				test: /\.(ts|tsx)$/,
				include: SRC_PATH,
				loader: 'awesome-typescript-loader',
				options: {
					useCache: true,
					forceIsolatedModules: true,
					reportFiles: ['src/**/*.{ts,tsx}'],
				},
			},
			{
				test: /\.css$/,
				use: [
					require.resolve('style-loader'),
					{
						loader: require.resolve('css-loader'),
						options: {
							importLoaders: 1,
							modules: 1,
							localIdentName: '[path]-[name]-[local]',
						},
					},
					{
						loader: require.resolve('postcss-loader'),
						options: {
							ident: 'postcss',
							plugins: () => [
								require('postcss-import'),
								require('postcss-cssnext')({
									features: {
										customProperties: false,
									},
								}),
							],
						},
					},
				],
				include: SRC_PATH,
			},
		],
	},
};
```

And here are the errors I'm getting
```
EMPconfig is not defined
ReferenceError: EMPconfig is not defined
    at Object.<anonymous> (http://localhost:9001/static/preview.bundle.js:14169:13)
    at __webpack_require__ (http://localhost:9001/static/preview.bundle.js:679:30)
    at fn (http://localhost:9001/static/preview.bundle.js:89:20)
    at Object.<anonymous> (http://localhost:9001/static/preview.bundle.js:102060:74)
    at __webpack_require__ (http://localhost:9001/static/preview.bundle.js:679:30)
    at fn (http://localhost:9001/static/preview.bundle.js:89:20)
    at Object.<anonymous> (http://localhost:9001/static/preview.bundle.js:131582:67)
    at __webpack_require__ (http://localhost:9001/static/preview.bundle.js:679:30)
    at fn (http://localhost:9001/static/preview.bundle.js:89:20)
    at Object.<anonymous> (http://localhost:9001/static/preview.bundle.js:11921:78)
ERROR in ./node_modules/css-loader??ref--3-1!./node_modules/postcss-loader/lib??postcss!./src/components/shared/groupsubmodule/GroupSubModule.css
Module build failed: Error: Failed to find 'components/variables.css'
  in [
    /Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/src/containers/article/broadcastmodule/broadcastsection/broadcasttree,
        /Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/src/containers/article/broadcastmodule/broadcastsection/broadcastselectedsections,
        /Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/src/containers/article/broadcastmodule/broadcastsection,
        /Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/src/containers/article/broadcastmodule/broadcastform,
        /Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/src/components/shared/groupsubmodule
  ]
    at resolveModule.catch.catch (/Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/node_modules/postcss-import/lib/resolve-id.js:35:13)
    at <anonymous>
 @ ./src/components/shared/groupsubmodule/GroupSubModule.css 4:14-164 19:20-170
 @ ./src/components/shared/groupsubmodule/GroupSubModule.tsx
 @ ./src/containers/article/broadcastmodule/broadcastsection/BroadcastFolder.tsx
 @ ./src/containers/article/broadcastmodule/BroadcastModuleBuilder.tsx
 @ ./stories/index.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js
ERROR in ./node_modules/css-loader??ref--3-1!./node_modules/postcss-loader/lib??postcss!./src/containers/article/broadcastmodule/broadcastform/BroadcastForm.css
Module build failed: Error: Failed to find 'components/variables.css'
  in [
    /Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/src/containers/article/broadcastmodule/broadcastsection/broadcasttree,
        /Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/src/containers/article/broadcastmodule/broadcastsection/broadcastselectedsections,
        /Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/src/containers/article/broadcastmodule/broadcastsection,
        /Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/src/containers/article/broadcastmodule/broadcastform,
        /Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/src/components/shared/groupsubmodule
  ]
    at resolveModule.catch.catch (/Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/node_modules/postcss-import/lib/resolve-id.js:35:13)
    at <anonymous>
 @ ./src/containers/article/broadcastmodule/broadcastform/BroadcastForm.css 4:14-169 19:20-175
 @ ./src/containers/article/broadcastmodule/broadcastform/BroadcastSearchForm.tsx
 @ ./src/containers/article/broadcastmodule/BroadcastModuleBuilder.tsx
 @ ./stories/index.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js
ERROR in ./node_modules/css-loader??ref--3-1!./node_modules/postcss-loader/lib??postcss!./src/containers/article/broadcastmodule/broadcastsection/BroadcastSection.css
Module build failed: Error: Failed to find 'components/variables.css'
  in [
    /Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/src/containers/article/broadcastmodule/broadcastsection/broadcasttree,
        /Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/src/containers/article/broadcastmodule/broadcastsection/broadcastselectedsections,
        /Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/src/containers/article/broadcastmodule/broadcastsection,
        /Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/src/containers/article/broadcastmodule/broadcastform,
        /Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/src/components/shared/groupsubmodule
  ]
    at resolveModule.catch.catch (/Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/node_modules/postcss-import/lib/resolve-id.js:35:13)
    at <anonymous>
 @ ./src/containers/article/broadcastmodule/broadcastsection/BroadcastSection.css 4:14-172 19:20-178
 @ ./src/containers/article/broadcastmodule/broadcastsection/BroadcastSection.tsx
 @ ./src/containers/article/broadcastmodule/BroadcastModuleBuilder.tsx
 @ ./stories/index.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js
ERROR in ./node_modules/css-loader??ref--3-1!./node_modules/postcss-loader/lib??postcss!./src/containers/article/broadcastmodule/broadcastsection/broadcasttree/BroadcastTreeBuilder.css
Module build failed: Error: Failed to find 'components/variables.css'
  in [
    /Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/src/containers/article/broadcastmodule/broadcastsection/broadcasttree,
        /Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/src/containers/article/broadcastmodule/broadcastsection/broadcastselectedsections,
        /Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/src/containers/article/broadcastmodule/broadcastsection,
        /Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/src/containers/article/broadcastmodule/broadcastform,
        /Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/src/components/shared/groupsubmodule
  ]
    at resolveModule.catch.catch (/Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/node_modules/postcss-import/lib/resolve-id.js:35:13)
    at <anonymous>
 @ ./src/containers/article/broadcastmodule/broadcastsection/broadcasttree/BroadcastTreeBuilder.css 4:14-182 19:20-188
 @ ./src/containers/article/broadcastmodule/broadcastsection/broadcasttree/BroadcastTreeBuilder.tsx
 @ ./src/containers/article/broadcastmodule/broadcastsection/BroadcastSection.tsx
 @ ./src/containers/article/broadcastmodule/BroadcastModuleBuilder.tsx
 @ ./stories/index.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js
ERROR in ./node_modules/css-loader??ref--3-1!./node_modules/postcss-loader/lib??postcss!./src/containers/article/broadcastmodule/broadcastsection/broadcastselectedsections/broadcastSelectedSections.css
Module build failed: Error: Failed to find 'components/variables.css'
  in [
    /Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/src/containers/article/broadcastmodule/broadcastsection/broadcasttree,
        /Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/src/containers/article/broadcastmodule/broadcastsection/broadcastselectedsections,
        /Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/src/containers/article/broadcastmodule/broadcastsection,
        /Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/src/containers/article/broadcastmodule/broadcastform,
        /Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/src/components/shared/groupsubmodule
  ]
    at resolveModule.catch.catch (/Users/heliosalves/Development/Projects/QMI/emp2.0/empfront/node_modules/postcss-import/lib/resolve-id.js:35:13)
    at <anonymous>
 @ ./src/containers/article/broadcastmodule/broadcastsection/broadcastselectedsections/broadcastSelectedSections.css 4:14-187 19:20-193
 @ ./src/containers/article/broadcastmodule/broadcastsection/broadcastselectedsections/broadcastSelectedSections.tsx
 @ ./src/containers/article/broadcastmodule/broadcastsection/BroadcastSection.tsx
 @ ./src/containers/article/broadcastmodule/BroadcastModuleBuilder.tsx
 @ ./stories/index.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js
```

I've already tried a couple of webpack configurations but no success. Any help would be appreciated.

Thanks

**Comment by igor-dv** [comment]
What storybook version do you use? Do you have any public repo with the reproduction?
