### ISSUE TITLE
yarn run storybook throws error

### ISSUE THREAD

**Issue by bret7** [storybooks/storybook#3647]
### Bug?

getstorybook

 ```
getstorybook - the simplest way to add a storybook to your project. 

 • Detecting project type. ✓
 • Adding storybook support to your "Create React App" based project. ✓
 • Preparing to install dependencies. ✓

yarn install v1.7.0
[1/4] 🔍  Resolving packages...
⠁ (node:13259) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
warning @storybook/react > airbnb-js-shims > array.prototype.flatten@1.2.1: This method has been renamed to "flat" - please use `array.prototype.flat` instead
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 17.06s.

 • Installing dependencies. ✓

To run your storybook, type:

   yarn run storybook 

For more information visit: https://storybook.js.org
```
yarn run storybook

```
yarn run v1.7.0
$ start-storybook -p 9009
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module 'find-cache-dir'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (.../test/node_modules/@storybook/react/dist/server/config.js:86:21)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (.../test/node_modules/@storybook/react/dist/server/index.js:17:15)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
error Command failed with exit code 1.
```

### Steps to reproduce

1. create a new react app with `create-react-app`
2. run `getstorybook` command in newly created app directory
3. run `yarn run storybook`
4. throws err

### Versions

yarn 1.7.0
node 10.2.0
react 16.4.0
react-dom 16.4.0

storybook/addon-actions 3.4.5
storybook/addon-links 3.4.5
storybook/addons 3.4.5
storybook/react 3.4.5

**Comment by bret7** [comment]
Fixed by running `npm install --save-dev find-cache-dir`

Not sure why it didn't run 'out of the box' though...

**Comment by ndelangen** [comment]
This is an actual bug it seems,

find-cache-dir is used in our codebase, but not our `package.json` 👎

**Comment by alexeyknyshev** [comment]
`bs-platform` getting-started is affected by this problem too

**Comment by rea1ftr** [comment]
internal/modules/cjs/loader.js:596
    throw err;

**Comment by ndelangen** [comment]
I just searched for it again, I can find it in the package.json of both core and app/react-native.

**Comment by neginbasiri** [comment]
Failed to load preset: "C:\\Projects\\storybook\\node_modules\\@storybook\\core\\dist\\server\\manager\\manager-preset.js"


Failed to load preset: "C:\\Projects\\storybook\\node_modules\\@storybook\\core\\dist\\server\\preview\\preview-preset.js"

 TypeError: Cannot read property 'rules' of undefined

**Comment by cope** [comment]
I added find-cache-dir, but the error remain 😞
