### ISSUE TITLE
[getstorybook]TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by zhaozhe0831** [storybooks/storybook#3658]
I'm not sure if not I meet a bug.

```bash
╭─zhaozhe@zhaozhe ~/Demo/vue-skeleton ‹ruby-2.2.1› ‹master*›
╰─➤  getstorybook -f

 getstorybook - the simplest way to add a storybook to your project.

 • Detecting project type. ✓
 • Adding storybook support to your "Single File Components Vue" app
     TypeError: Cannot read property 'find' of undefined
    at _callee$ (/usr/local/lib/node_modules/@storybook/cli/generators/SFC_VUE/index.js:54:21)
    at tryCatch (/usr/local/lib/node_modules/@storybook/cli/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/@storybook/cli/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/@storybook/cli/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/usr/local/lib/node_modules/@storybook/cli/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/@storybook/cli/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
╭─zhaozhe@zhaozhe ~/Demo/vue-skeleton ‹ruby-2.2.1› ‹master*›
╰─➤  getstorybook -V                                                                                                                                            1 ↵
3.4.6
```

If you need, I have more info. Such as `package.json`?

**Comment by shilman** [comment]
Hi @zhaozhe0831 I tried reproing this with `@vue/cli@3.0.0-beta.11` and `@storybook/cli@3.4.6` but it works fine. The line it's erroring on is:

```
  const babelRc = getBabelRc() || {
    presets: [['env', { modules: false }]],
  };
  const hasPreset = babelRc.presets.find(
    preset =>
      (Array.isArray(preset) && preset[0] === 'vue') ||
      (typeof preset === 'string' && preset === 'vue')
  );
  if (!hasPreset) {
    babelRc.presets.push('vue');
  }
```
Which means that you have a babelrc but it doesn't have presets. It looks like it could be a bug in our code, but if you can tell me more about your babel setup that would help me understand a bit better. Thanks!

**Comment by zhaozhe0831** [comment]
babelrc？Let me check it.

**Comment by zhaozhe0831** [comment]
I create another issue.
https://github.com/storybooks/storybook/issues/3677
