### ISSUE TITLE
Addon backgrounds not compatible with Polymer

### ISSUE THREAD

**Issue by hellokatili** [storybooks/storybook#3721]
I know, Storybook with Polymer is still under development. But the [Addon / Framework Support Table](https://github.com/storybooks/storybook/blob/v4.0.0-alpha.8/ADDONS_SUPPORT.md) states that it's supported.

Anyway... the backgrounds addon does not seem be compatible with storybook/polymer v4.0.0-alpha.8:

**Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.**

### Full error message:
```
Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
            TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at renderMain (http://localhost:6006/static/preview.bundle.js:21087:17)
    at renderMain (http://localhost:6006/static/preview.bundle.js:20429:5)
    at renderUI (http://localhost:6006/static/preview.bundle.js:20448:9)
    at Object.dispatch (http://localhost:6006/static/preview.bundle.js:57828:7)
    at ConfigApi._renderMain (http://localhost:6006/static/preview.bundle.js:20066:24)
    at render (http://localhost:6006/static/preview.bundle.js:20013:17)
    at ConfigApi.configure (http://localhost:6006/static/preview.bundle.js:20042:9)
    at Module.<anonymous> (http://localhost:6006/static/preview.bundle.js:810:69)
    at Module../.storybook/config.js (http://localhost:6006/static/preview.bundle.js:811:30)
    at __webpack_require__ (http://localhost:6006/static/preview.bundle.js:717:30)
```

### Steps to reproduce

I downloaded the demo https://github.com/stijnkoopal/polymer-storybook by @stijnkoopal and tried to add the backgrounds addon following the instructions [here](https://github.com/storybooks/storybook/tree/v4.0.0-alpha.8/addons/backgrounds). (See my button.stories.js file below.)

### Code Snippets

**button.stories.js**
```js
import {storiesOf} from '@storybook/polymer';
import backgrounds from '@storybook/addon-backgrounds';

storiesOf("Button", module)
  .addDecorator(backgrounds([
    { name: "twitter", value: "#00aced", default: true },
    { name: "facebook", value: "#3b5998" }
  ]))
  .add("with text", () => '<button>Click me</button>');
```
(I replaced the actual Polymer component with the `<button>` element to simplify the test case. The error stays the same.)

### Storybook version and installed addons:

- storybook/polymer 4.0.0-alpha.8
- storybook/addon-actions 4.0.0-alpha.8
- storybook/addon-backgrounds 3.4.6
- storybook/addon-knobs 4.0.0-alpha.8
- storybook/addon-viewport 4.0.0-alpha.8

**Comment by igor-dv** [comment]
I've added an example to our official polymer examples

https://deploy-preview-3727--storybooks-polymer.netlify.com/?selectedKind=Addon%7CBackgrounds&selectedStory=button%20with%20text&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

Anyway, you should upgrade `storybook/addon-backgrounds` from 3.4.6 to 4.0.0-alpha.8 as well (In the previous versions, it was not framework agnostic).

**Comment by hellokatili** [comment]
Yeah! The upgrade to 4.0.0-alpha.8 works!
Thank you!
