### ISSUE TITLE
Ref to Angular type failing only in Storybook

### ISSUE THREAD

**Issue by jonrimmer** [storybooks/storybook#3925]
### Bug summary

I have an Angular component that produces a `ReferenceError: TemplateRef is not defined` error, but only when run in Storybook. It seems to be due to an issue with how the Angular code is compiled by Storybook.

### Steps to reproduce

Clone this repo:

https://github.com/jonrimmer/storybook-import-issue

It is a slightly modified version of the `ng new` project.

The `AppComponent` has been changed to define the following input property:

```js
_ref: TemplateRef<any> | null;

@Input()
get ref() { return this._ref; }
set ref(value: TemplateRef<any> | null) { this._ref = value; }
```

When the app is loaded using `npm run start`, this works fine. But when it is loaded through Storybook using `npm run storybook`, it produces an error:

```
ReferenceError: TemplateRef is not defined
    at http://localhost:9001/static/preview.bundle.js:116424:42
    at Module../src/app/app.component.ts (http://localhost:9001/static/preview.bundle.js:116434:2)
    at __webpack_require__ (http://localhost:9001/static/preview.bundle.js:725:30)
    at fn (http://localhost:9001/static/preview.bundle.js:102:20)
    at Module.<anonymous> (http://localhost:9001/static/preview.bundle.js:116451:72)
    at Module../src/app/app.stories.ts (http://localhost:9001/static/preview.bundle.js:116462:30)
    at __webpack_require__ (http://localhost:9001/static/preview.bundle.js:725:30)
    at fn (http://localhost:9001/static/preview.bundle.js:102:20)
    at loadStories (http://localhost:9001/static/preview.bundle.js:811:3)
    at ConfigApi._renderMain (http://localhost:9001/static/preview.bundle.js:64035:20)
```

Digging into the raw code for `preview.bundle.js` in devtools, it looks like there is an issue lies in the Angular reflection metadata emitted. It has is a reference to `TemplateRef` that has not been mangled with the correct `__WEBPACK_IMPORTED_MODULE_` junk.

Since this works when run using `ng`, I presume there must be some difference in how Storybook is compiling vs the CLI that is resulting in this problem.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/angular 4.0.0-alpha.14

### Affected platforms 

Angular: v6 
I tried a few 6.0.x versions. and 6.1, but it didn't make any difference.

**Comment by jonrimmer** [comment]
It turns out this is a TypeScript bug: https://github.com/Microsoft/TypeScript/issues/26003
