### ISSUE TITLE
Storybook seems to use other Webpack version than it requires (Webpack 4 over 3). 

### ISSUE THREAD

**Issue by ilyanoskov** [storybooks/storybook#3952]
### Bug summary

In my project I want to use Docz for documentation. Docz requires Webpack 4 to build itself. After installing docz, `yarn build:storybook` no longer works and I get this error:

```
info => Loading custom webpack config (full-control mode).
info Building storybook ...
/Users/ilyanoskov/Sumup/circuit-ui/node_modules/webpack/lib/DefinePlugin.js:93
                compiler.hooks.compilation.tap(
                               ^
TypeError: Cannot read property 'compilation' of undefined
    at DefinePlugin.apply (/Users/ilyanoskov/Sumup/circuit-ui/node_modules/webpack/lib/DefinePlugin.js:93:18)
    at Compiler.apply (/Users/ilyanoskov/Sumup/circuit-ui/node_modules/@storybook/core/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/Users/ilyanoskov/Sumup/circuit-ui/node_modules/@storybook/core/node_modules/webpack/lib/webpack.js:33:19)
    at buildStatic (/Users/ilyanoskov/Sumup/circuit-ui/node_modules/@storybook/core/dist/server/build-static.js:107:40)
    at Object.<anonymous> (/Users/ilyanoskov/Sumup/circuit-ui/node_modules/@storybook/react/dist/server/build.js:23:25)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ilyanoskov/Sumup/circuit-ui/node_modules/@storybook/react/bin/build.js:3:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
```

### Steps to reproduce

Any project that uses storybook would probably fit here. Then installing Docz and trying to build storybook will break the build process.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 3.4.0

**Comment by igor-dv** [comment]
You can upgrade to the latest alpha version of Storybook to be compatible with webpack v4. 
Or did you want to have Storybook working with webpack v3 while Docz with webpack v4?

**Comment by ilyanoskov** [comment]
@igor-dv yes, is it possible so that Storybook uses its own version of webpack while docz uses its own?

**Comment by igor-dv** [comment]
Can you share your custom `.storybook/webpack.config.js` ?

**Comment by igor-dv** [comment]
I think here

```js
const webpack = require('webpack');
```

It's resolved to the v4. Try to change this to the pass of webpack that is used in storybook... It might be something like:

```js
const webpack = require('@storybook/react/node_modules/webpack');
```

**Comment by ilyanoskov** [comment]
@igor-dv that's right! it worked :) thank you very much!!!

**Comment by airtonix** [comment]
I get this error even without a custom `webpack.config.js`.

**Comment by codejamninja** [comment]
Same, I think the internal storybook webpack config is resolving to the wrong place. How can we resolve it to the v3 webpack.

**Comment by xujianshe** [comment]
> Same, I think the internal storybook webpack config is resolving to the wrong place. How can we resolve it to the v3 webpack.

i think you are right,  Is there any further research?
