### ISSUE TITLE
Storybook fails to start when project is updated to Webpack 4

### ISSUE THREAD

**Issue by rkclark** [storybooks/storybook#3975]
### Bug or support request summary

After upgrading webpack to v4 in my project, storybook fails to start. It appears to be trying to use webpack from the project's node_modules, rather than the version of webpack from its own dependencies. Similar to #3952, but the solution provided in that issue does not work in my case.

### Steps to reproduce

1) Setup storybook with this config:

```js
const merge = require('webpack-merge');
const path = require('path');
const cssVariables = require('postcss-css-variables')();
const autoprefixer = require('autoprefixer');
const InjectHtmlPlugin = require('./InjectHtmlPlugin');
const publicEnvVars = require('../config/publicEnvVars');

const srcPath = path.join(__dirname, '../src');


module.exports = function(storybookBaseConfig, configType) {
  const isProduction = configType === 'PRODUCTION';

  const ourConfig = {
    module: {
      rules: [
        {
          test: /\.css$/,
          include: [
            path.join(srcPath, 'routes'),
            path.join(srcPath, 'components'),
          ],
          use: [
            require.resolve('style-loader'),
            {
              loader: require.resolve('css-loader'),
              options: {
                modules: true,
                importLoaders: 1,
                localIdentName: '[name]__[local]--[hash:base64:5]',
                camelCase: true,
              },
            },
            {
              loader: require.resolve('postcss-loader'),
              options: {
                ident: 'postcss', // https://webpack.js.org/guides/migrating/#complex-options
                plugins: () => [
                  require('postcss-flexbugs-fixes'),
                  require('postcss-import'),
                  cssVariables,
                  require('postcss-custom-media'),
                  autoprefixer({
                    browsers: [
                      '>1%',
                      'iOS > 8',
                      'last 4 versions',
                      'Firefox ESR',
                      'not ie < 9', // React doesn't support IE8 anyway
                    ],
                    flexbox: 'no-2009',
                  }),
                ],
              },
            },
          ],
        },
        {
          test: /\.css$/,
          include: path.join(srcPath, 'css'),
          use: [
            require.resolve('style-loader'),
            {
              loader: require.resolve('css-loader'),
              options: {
                importLoaders: 1,
              },
            },
            {
              loader: require.resolve('postcss-loader'),
              options: {
                ident: 'postcss', // https://webpack.js.org/guides/migrating/#complex-options
                plugins: () => [
                  require('postcss-flexbugs-fixes'),
                  require('postcss-import'),
                  cssVariables,
                  require('postcss-custom-media'),
                  autoprefixer({
                    browsers: [
                      '>1%',
                      'iOS > 8',
                      'last 4 versions',
                      'Firefox ESR',
                      'not ie < 9', // React doesn't support IE8 anyway
                    ],
                    flexbox: 'no-2009',
                  }),
                ],
              },
            },
          ],
        },
        {
          test: /\.(png|jpg|gif|svg)$/,
          loader: require.resolve('file-loader'),
          options: {
            limit: 10000,
            name: '[path][name].[ext]',
          },
        },
        {
          test: /\.(png|woff|woff2|eot|ttf|svg)$/,
          loader: require.resolve('url-loader'),
          options: {
            limit: 10000,
          },
        }
      ],
    },
    plugins: [
      new InjectHtmlPlugin(publicEnvVars),
    ]
  };

  return merge(storybookBaseConfig, ourConfig);
};
```

When webpack 2 or 3 is installed in the project's `package.json`, this config file works and storybook opens as normal.

2) Upgrade webpack to v4 in project's dependencies.

3) Try to start storybook, it will now error with:

```sh
info @storybook/react v3.4.8
info
info => Loading static files from: /Users/rickclark/ctm/rewards/rewards.user-journey .
info => Loading custom .babelrc
info => Loading custom addons config.
info => Loading custom webpack config (full-control mode).
/Users/rickclark/ctm/rewards/rewards.user-journey/node_modules/webpack/lib/DefinePlugin.js:93
		compiler.hooks.compilation.tap(
		               ^

TypeError: Cannot read property 'compilation' of undefined
    at DefinePlugin.apply (/Users/rickclark/ctm/rewards/rewards.user-journey/node_modules/webpack/lib/DefinePlugin.js:93:18)
    at Compiler.apply (/Users/rickclark/ctm/rewards/rewards.user-journey/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/Users/rickclark/ctm/rewards/rewards.user-journey/node_modules/@storybook/core/node_modules/webpack/lib/webpack.js:33:19)
    at exports.default (/Users/rickclark/ctm/rewards/rewards.user-journey/node_modules/@storybook/core/dist/server/middleware.js:29:40)
    at buildDev (/Users/rickclark/ctm/rewards/rewards.user-journey/node_modules/@storybook/core/dist/server/build-dev.js:163:36)
    at Object.<anonymous> (/Users/rickclark/ctm/rewards/rewards.user-journey/node_modules/@storybook/react/dist/server/index.js:23:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/rickclark/ctm/rewards/rewards.user-journey/node_modules/@storybook/react/bin/index.js:3:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
```

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 3.4.8

### Affected platforms 

MacOS

**Comment by sutangu** [comment]
You need to use **4.0.0-alpha.16** version today for working w/ Webpack4.

**Comment by rkclark** [comment]
Thanks, I'm aware that is an option but in #3952 a solution was described where webpack 4 could be used at the project level and storybook could use its own webpack dependency. That's what I would like to try and achieve.

**Comment by rkclark** [comment]
I tried the alpha version but had some issues so thought it would be better to stick with a stable version

**Comment by igor-dv** [comment]
So didn't #3952 help you?

**Comment by rkclark** [comment]
Unfortunately not, we've moved over to React Cosmos now @igor-dv
