### ISSUE TITLE
Regression in v4 alpha.15 with Vue

### ISSUE THREAD

**Issue by ernestoalejo** [storybooks/storybook#4000]
### Bug or support request summary

Fails to build when using Vue:

```
info @storybook/vue v4.0.0-alpha.15
info 
info => Loading static files from: /MYFOLDER/assets .
info => Loading custom addons config.
WARN => Custom configuration file /MYFOLDER/.storybook/webpack.config.js is detected
WARN    but impossible to import loader for .js
info => Loading custom webpack config (extending mode).
/MYFOLDER/node_modules/vue-loader/lib/plugin.js:58
      throw new Error(
      ^

Error: [VueLoaderPlugin Error] No matching use for vue-loader is found.
Make sure the rule matching .vue files include vue-loader in its use.
    at VueLoaderPlugin.apply (/MYFOLDER/node_modules/vue-loader/lib/plugin.js:58:13)
    at webpack (/MYFOLDER/node_modules/webpack/lib/webpack.js:37:12)
    at exports.default (/MYFOLDER/node_modules/@storybook/core/dist/server/middleware.js:34:40)
    at buildDev (/MYFOLDER/node_modules/@storybook/core/dist/server/build-dev.js:167:36)
    at Object.<anonymous> (/MYFOLDER/node_modules/@storybook/vue/dist/server/index.js:11:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

Same files with the previous version:

```
info @storybook/vue v4.0.0-alpha.14
info 
info => Loading static files from: /MYFOLDER/assets .
info => Loading custom addons config.
WARN => Custom configuration file /MYFOLDER/.storybook/webpack.config.js is detected
WARN    but impossible to import loader for .js
info => Loading custom webpack config (extending mode).
 10% building modules 2/2 modules 0 activeℹ ｢wdm｣: wait until bundle finished:     
webpack built 026bf83ba54df68ee0f7 in 6398ms                                                          
ℹ ｢wdm｣: Hash: 026bf83ba54df68ee0f7
Version: webpack 4.15.0
Time: 6398ms
Built at: .......[rest of the output]
```

### Steps to reproduce

1. Have a custom `webpack.config.js`.
2. Run `start-storybook -p 6006`, it should trigger the error.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/vue 4.0.0-alpha.15 (4.0.0-alpha.16 tested too, same error)
- vue-loader 15.3.0

Working in `4.0.0-alpha.14`.

### Screenshots / Screencast / Code Snippets (Optional)

**/.storybook/webpack.config.js:**
```js

const VueLoaderPlugin = require('vue-loader/lib/plugin');


module.exports = {
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'babel-loader',
          },
        ],
      },
    ],
  },
  plugins: [
    new VueLoaderPlugin(),
  ],
  resolve: {
    alias: {
      'vue$': 'vue/dist/vue.esm.js',
    },
  },
};
```

**Comment by pksunkara** [comment]
We added `VueLoaderPlugin` to `@storybook/vue` on alpha.15 ([commit](https://github.com/storybooks/storybook/commit/a9e57efe22e2d04816f7afd6da4ff265dedd7109)). It is probably making a difference to your old configuration file. Can you edit your webpack.config.js keeping the above commit in mind?

**Comment by ernestoalejo** [comment]
Removing the loader plugin worked ok:

```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'babel-loader',
          },
        ],
      },
    ],
  },
  resolve: {
    alias: {
      'vue$': 'vue/dist/vue.esm.js',
    },
  },
};
```


Thank you!
