### ISSUE TITLE
vue-kitchen-sink demo fails to build

### ISSUE THREAD

**Issue by tony19** [storybooks/storybook#4020]
### Bug or support request summary
Attempting to build `vue-kitchen-sink` results in a prompt to install `webpack-cli` or `webpack-command`. Typing in either one results in an installation failure (module not found).

### Steps to reproduce
 1. Clone `storybook` repo (`master` branch - `93745d7` as of today)

        git clone https://github.com/storybooks/storybook.git

 2. CD into `vue-kitchen-sink`:

        cd storybook/examples/vue-kitchen-sink

 3. Install node modules:

        npm install

 4. Build project:

        npm run build

### Affected platforms 

 * macOS High Sierra 10.13.6
 * node 10.5.0
 
### Screenshots / Screencast / Code Snippets (Optional)

```
➜  vue-kitchen-sink git:(master) npm i

> fsevents@1.2.4 install /Users/tony/src/tmp/storybook/examples/vue-kitchen-sink/node_modules/fsevents
> node install

[fsevents] Success: "/Users/tony/src/tmp/storybook/examples/vue-kitchen-sink/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
added 1231 packages from 911 contributors and audited 28472 packages in 12.817s
found 0 vulnerabilities

➜  vue-kitchen-sink git:(master) npm run build

> vue-example@4.0.0-alpha.16 build /Users/tony/src/tmp/storybook/examples/vue-kitchen-sink
> cross-env NODE_ENV=production webpack --progress --hide-modules

One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
 - webpack-cli (https://github.com/webpack/webpack-cli)
   The original webpack full-featured CLI.
 - webpack-command (https://github.com/webpack-contrib/webpack-command)
   A lightweight, opinionated webpack CLI.
We will use "npm" to install the CLI via "npm install -D".
Which one do you like to install (webpack-cli/webpack-command):
webpack-cli
Installing 'webpack-cli' (running 'npm install -D webpack-cli')...
npm WARN @storybook/vue@4.0.0-alpha.16 requires a peer of vue@2.5.16 but none is installed. You must install peer dependencies yourself.
npm WARN @storybook/vue@4.0.0-alpha.16 requires a peer of vue-template-compiler@2.5.16 but none is installed. You must install peer dependencies yourself.
npm WARN jest-specific-snapshot@1.0.0 requires a peer of jest@* but none is installed. You must install peer dependencies yourself.
npm WARN react-datetime@2.15.0 requires a peer of moment@>=2.16.0 but none is installed. You must install peer dependencies yourself.

audited 28616 packages in 8.789s
found 0 vulnerabilities

{ Error: Cannot find module 'webpack-cli'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at runCommand.then (/Users/tony/src/tmp/storybook/examples/vue-kitchen-sink/node_modules/webpack/bin/webpack.js:152:5)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-example@4.0.0-alpha.16 build: `cross-env NODE_ENV=production webpack --progress --hide-modules`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-example@4.0.0-alpha.16 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tony/.npm/_logs/2018-08-16T06_46_08_141Z-debug.log
➜  vue-kitchen-sink git:(master) ✗ 
```

**Comment by igor-dv** [comment]
Please read [here](https://github.com/storybooks/storybook/blob/master/CONTRIBUTING.md) about how to bootstrap the monorepo.
