### ISSUE TITLE
npm ERR! Unexpected end of JSON input while parsing near '...qH9wt7R9IIVZ+K7ShzfpL'

### ISSUE THREAD

**Issue by EnterRavement** [storybooks/storybook#4034]
Hey, I wanted to install Storybook the way it is described, but it tells me, that nomnom is no longer supported. It also advices me to upgrade the babel-preset.

The reason it is not installing though is this weird unexpected end of JSON input

 Full Log: 
```

npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please r
ead babeljs.io/env to update!
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm ERR! Unexpected end of JSON input while parsing near '...qH9wt7R9IIVZ+K7ShzfpL'
```
```


0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\bjoer\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   '@storybook/cli' ]
2 info using npm@6.1.0
3 info using node@v10.5.0
4 verbose npm-session 03d1e810eb9dcf11
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/@storybook%2fcli 46ms (from cache)
8 silly pacote tag manifest for @storybook/cli@latest fetched in 121ms
9 timing stage:loadCurrentTree Completed in 503ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 5ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule @storybook/cli@3.4.10 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/@storybook%2fcodemod 154ms (from cache)
18 silly pacote version manifest for @storybook/codemod@3.4.10 fetched in 162ms
19 silly resolveWithNewModule @storybook/codemod@3.4.10 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/babel-register 1033ms (from cache)
21 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-runtime 1035ms (from cache)
22 http fetch GET 304 https://registry.npmjs.org/babel-preset-env 1040ms (from cache)
23 silly pacote range manifest for babel-register@^6.26.0 fetched in 1043ms
24 silly resolveWithNewModule babel-register@6.26.0 checking installable status
25 silly pacote range manifest for babel-plugin-transform-runtime@^6.23.0 fetched in 1047ms
26 silly resolveWithNewModule babel-plugin-transform-runtime@6.23.0 checking installable status
27 silly pacote range manifest for babel-preset-env@^1.6.0 fetched in 1057ms
28 silly resolveWithNewModule babel-preset-env@1.7.0 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/child-process-promise 1066ms (from cache)
30 silly pacote range manifest for child-process-promise@^2.2.1 fetched in 1073ms
31 silly resolveWithNewModule child-process-promise@2.2.1 checking installable status
32 http fetch GET 304 https://registry.npmjs.org/babel-runtime 1087ms (from cache)
33 silly pacote range manifest for babel-runtime@^6.26.0 fetched in 1095ms
34 silly resolveWithNewModule babel-runtime@6.26.0 checking installable status
35 http fetch GET 304 https://registry.npmjs.org/json5 1065ms (from cache)
36 http fetch GET 304 https://registry.npmjs.org/cross-spawn 1222ms (from cache)
37 http fetch GET 304 https://registry.npmjs.org/jscodeshift 1222ms (from cache)
38 http fetch GET 304 https://registry.npmjs.org/chalk 1226ms (from cache)
39 http fetch GET 304 https://registry.npmjs.org/commander 1226ms (from cache)
40 silly pacote range manifest for json5@^0.5.1 fetched in 1074ms
41 silly resolveWithNewModule json5@0.5.1 checking installable status
42 silly pacote range manifest for cross-spawn@^6.0.5 fetched in 1230ms
43 silly resolveWithNewModule cross-spawn@6.0.5 checking installable status
44 silly pacote range manifest for chalk@^2.3.2 fetched in 1232ms
45 silly resolveWithNewModule chalk@2.4.1 checking installable status
46 silly pacote range manifest for jscodeshift@^0.5.0 fetched in 1232ms
47 silly resolveWithNewModule jscodeshift@0.5.1 checking installable status
48 silly pacote range manifest for commander@^2.15.0 fetched in 1233ms
49 silly resolveWithNewModule commander@2.17.1 checking installable status
50 http fetch GET 304 https://registry.npmjs.org/merge-dirs 332ms (from cache)
51 silly pacote range manifest for merge-dirs@^0.2.1 fetched in 339ms
52 silly resolveWithNewModule merge-dirs@0.2.1 checking installable status
53 http fetch GET 304 https://registry.npmjs.org/shelljs 408ms (from cache)
54 http fetch GET 304 https://registry.npmjs.org/semver 423ms (from cache)
55 silly pacote range manifest for shelljs@^0.8.1 fetched in 415ms
56 silly resolveWithNewModule shelljs@0.8.2 checking installable status
57 silly pacote range manifest for semver@^5.5.0 fetched in 428ms
58 silly resolveWithNewModule semver@5.5.0 checking installable status
59 http fetch GET 304 https://registry.npmjs.org/update-notifier 420ms (from cache)
60 silly pacote range manifest for update-notifier@^2.3.0 fetched in 427ms
61 silly resolveWithNewModule update-notifier@2.5.0 checking installable status
62 http fetch GET 304 https://registry.npmjs.org/babel-preset-stage-1 172ms (from cache)
63 http fetch GET 304 https://registry.npmjs.org/babel-preset-es2015 177ms (from cache)
64 http fetch GET 304 https://registry.npmjs.org/babel-plugin-transform-flow-strip-types 180ms (from cache)
65 silly pacote range manifest for babel-preset-stage-1@^6.5.0 fetched in 179ms
66 silly resolveWithNewModule babel-preset-stage-1@6.24.1 checking installable status
67 silly pacote range manifest for babel-plugin-transform-flow-strip-types@^6.8.0 fetched in 187ms
68 silly resolveWithNewModule babel-plugin-transform-flow-strip-types@6.22.0 checking installable status
69 silly pacote range manifest for babel-preset-es2015@^6.9.0 fetched in 188ms
70 warn deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
71 silly resolveWithNewModule babel-preset-es2015@6.24.1 checking installable status
72 http fetch GET 304 https://registry.npmjs.org/node-dir 290ms (from cache)
73 http fetch GET 304 https://registry.npmjs.org/colors 296ms (from cache)
74 silly fetchPackageMetaData error for colors@^1.1.2 Unexpected end of JSON input while parsing near '...qH9wt7R9IIVZ+K7ShzfpL'
75 http fetch GET 304 https://registry.npmjs.org/flow-parser 299ms (from cache)
76 http fetch GET 304 https://registry.npmjs.org/lodash 301ms (from cache)
77 silly pacote version manifest for node-dir@0.1.8 fetched in 300ms
78 silly resolveWithNewModule node-dir@0.1.8 checking installable status
79 http fetch GET 304 https://registry.npmjs.org/neo-async 304ms (from cache)
80 http fetch GET 304 https://registry.npmjs.org/micromatch 306ms (from cache)
81 http fetch GET 304 https://registry.npmjs.org/babylon 311ms (from cache)
82 silly pacote range manifest for flow-parser@^0.* fetched in 314ms
83 silly resolveWithNewModule flow-parser@0.79.0 checking installable status
84 silly pacote range manifest for lodash@^4.13.1 fetched in 314ms
85 silly resolveWithNewModule lodash@4.17.10 checking installable status
86 silly pacote range manifest for neo-async@^2.5.0 fetched in 316ms
87 silly resolveWithNewModule neo-async@2.5.2 checking installable status
88 silly pacote range manifest for micromatch@^2.3.7 fetched in 317ms
89 silly resolveWithNewModule micromatch@2.3.11 checking installable status
90 silly pacote range manifest for babylon@^7.0.0-beta.47 fetched in 323ms
91 silly resolveWithNewModule babylon@7.0.0-beta.47 checking installable status
92 http fetch GET 304 https://registry.npmjs.org/temp 405ms (from cache)
93 silly pacote range manifest for temp@^0.8.1 fetched in 411ms
94 silly resolveWithNewModule temp@0.8.3 checking installable status
95 http fetch GET 304 https://registry.npmjs.org/recast 458ms (from cache)
96 silly pacote range manifest for recast@^0.15.0 fetched in 465ms
97 silly resolveWithNewModule recast@0.15.3 checking installable status
98 http fetch GET 304 https://registry.npmjs.org/write-file-atomic 1043ms (from cache)
99 silly pacote range manifest for write-file-atomic@^1.2.0 fetched in 1049ms
100 silly resolveWithNewModule write-file-atomic@1.3.4 checking installable status
101 http fetch GET 304 https://registry.npmjs.org/nomnom 1258ms (from cache)
102 silly pacote range manifest for nomnom@^1.8.1 fetched in 1264ms
103 warn deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
104 silly resolveWithNewModule nomnom@1.8.1 checking installable status
105 timing stage:rollbackFailedOptional Completed in 1ms
106 timing stage:runTopLevelLifecycles Completed in 3518ms
107 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...qH9wt7R9IIVZ+K7ShzfpL'
107 verbose stack     at JSON.parse (<anonymous>)
107 verbose stack     at parseJson (C:\Users\bjoer\AppData\Roaming\npm\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
107 verbose stack     at consumeBody.call.then.buffer (C:\Users\bjoer\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\body.js:96:50)
107 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
108 verbose cwd C:\Users\bjoer\Desktop\Component Directory
109 verbose Windows_NT 10.0.17134
110 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\bjoer\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "@storybook/cli"
111 verbose node v10.5.0
112 verbose npm  v6.1.0
113 error Unexpected end of JSON input while parsing near '...qH9wt7R9IIVZ+K7ShzfpL'
114 verbose exit [ 1, true ]
```

**Comment by igor-dv** [comment]
I am not sure this is related to Storybook, but to the network/npm/environment problem. 
Can't do with this anything without a reproduction.

**Comment by alflennik** [comment]
I just encountered the same error running a brand new Storybook 5.0.10, Webpack 4.29.0, Babel 7.2.2, which makes me think that this error must be related to a low-level dependency, since these high level dependencies must have changed significantly since the issue was opened a year and a half ago.

I'm running a yarn monorepo.

Here's the stack trace:

```
yarn run v1.13.0
$ start-storybook -p 4001 --quiet --ci
info @storybook/react v5.0.10
info 
info => Loading presets
info => Loading presets
info => Loading custom addons config.
info => Loading custom webpack config (full-control mode).
info => Using base config because react-scripts is not installed.


WARN force closed preview build


WARN FATAL broken build!, will close the process,
WARN Fix the error below and restart storybook.

ERR! SyntaxError: Cannot parse records: Unexpected end of JSON input while parsing near ''
ERR!     at JSON.parse (<anonymous>)
ERR!     at parseJson (/Users/me/project/node_modules/json-parse-better-errors/index.js:7:17)
ERR!     at Array.inputFileSystem.readFile (/Users/me/project/node_modules/webpack/lib/Compiler.js:490:21)
ERR!     at Storage.finished (/Users/me/project/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
ERR!     at provider (/Users/me/project/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
ERR!     at /Users/me/project/node_modules/graceful-fs/graceful-fs.js:90:16
ERR!     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
ERR!  { SyntaxError: Cannot parse records: Unexpected end of JSON input while parsing near ''
ERR!     at JSON.parse (<anonymous>)
ERR!     at parseJson (/Users/me/project/node_modules/json-parse-better-errors/index.js:7:17)
ERR!     at Array.inputFileSystem.readFile (/Users/me/project/node_modules/webpack/lib/Compiler.js:490:21)
ERR!     at Storage.finished (/Users/me/project/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
ERR!     at provider (/Users/me/project/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
ERR!     at /Users/me/project/node_modules/graceful-fs/graceful-fs.js:90:16
ERR!     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
ERR!   stack:
ERR!    "SyntaxError: Cannot parse records: Unexpected end of JSON input while parsing near ''\n    at JSON.parse (<anonymous>)\n    at parseJson (/Users/me/project/node_modules/json-parse-better-errors/index.js:7:17)\n    at Array.inputFileSystem.readFile (/Users/me/project/node_modules/webpack/lib/Compiler.js:490:21)\n    at Storage.finished (/Users/me/project/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)\n    at provider (/Users/me/project/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)\n    at /Users/me/project/node_modules/graceful-fs/graceful-fs.js:90:16\n    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)" }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I was able to fix it by manually deleting my node_modules and rerunning yarn.

My instinct is that this is a yarn issue - monorepos are relatively unstable still.

**Comment by thclark** [comment]
I've had a very similar problem. It's occurred a couple of times during storybook builds in which there has been a build error of some kind. I think what must happen is that part of the build cache gets corrupted (perhaps an exception in the build is handled incorrectly, and a JSON file is unclosed, or gets written blank).

In my case the error could be traced to `node_modules/.cache` directory. Deleting this `.cache` directory fixes the problem, and saves deleting the whole of `node_modules`. The next storybook build will be longer than usual, of course :)

```
ERR! SyntaxError: /Users/me/myproject/node_modules/.cache/storybook/dev-server/325c8f456729b912b0d2134054eb7448-41ac79ddc5290d504ad69ef1fe8200a7: Unexpected end of JSON input
ERR!     at JSON.parse (<anonymous>)
ERR!     at /Users/me/myproject/node_modules/file-system-cache/node_modules/jsonfile/index.js:36:18
ERR!     at /Users/me/myproject/node_modules/graceful-fs/graceful-fs.js:123:16
ERR!     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
ERR!  SyntaxError: /Users/me/myproject/node_modules/.cache/storybook/dev-server/325c8f456729b912b0d2134054eb7448-41ac79ddc5290d504ad69ef1fe8200a7: Unexpected end of JSON input
ERR!     at JSON.parse (<anonymous>)
ERR!     at /Users/me/myproject/node_modules/file-system-cache/node_modules/jsonfile/index.js:36:18
ERR!     at /Users/me/myproject/node_modules/graceful-fs/graceful-fs.js:123:16
ERR!     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
```

**Comment by johnnyoshika** [comment]
@thclark Thank you! Deleting the `node_modules/.cache` directory as you suggested fixed it for me as well.
