### ISSUE TITLE
Jest fails with storyshot webpack 4 and storybook alpha

### ISSUE THREAD

**Issue by wing92300** [storybooks/storybook#4055]
#### What did you expect to happen?
After running Jest with Storyshot add-on correctly installed, my test should pass and snapshot should be generated.

#### What happened instead?
After running Jest, I get this error `Cannot find module '@storybook/react/dist/server/babel_config' from 'config-loader.js'`

![capture](https://user-images.githubusercontent.com/29124144/44456251-54ef9b80-a600-11e8-9927-69294658a7c8.JPG)

### Steps to reproduce
- Given the list of packages below
- Install storybook-react and needed dependencies 
- Run `jest`

### Please specify which version of Storybook and optionally any affected addons that you're running
package.json :

    "@storybook/addon-actions": "^3.4.8",
    "@storybook/addon-links": "^3.4.8",
    "@storybook/addon-storyshots": "^3.4.10",
    "@storybook/addons": "^3.4.8",
    "@storybook/cli": "^3.4.10",
    "@storybook/react": "^4.0.0-alpha.16",

    "webpack": "^4.16.3",
    "webpack-cli": "^3.1.0",
    "webpack-dev-server": "^3.1.5",
    "webpack-merge": "^4.1.3"

jest.config.js : 

``` javascript
const registerRequireContextHook = require('babel-plugin-require-context-hook/register')
registerRequireContextHook()

module.exports = {
  // Fix JSDOM bug : See issue https://github.com/facebook/jest/issues/6766
  testURL: 'http://localhost/'
}
```

.babelrc :
```
{
  "presets": [
    ["env",
    {
      "targets": {
        "browsers": ["last 5 Chrome versions"]
      }
    }],
    "react",
    "stage-2"
  ],
  "env": {
    "test": {
      "plugins": ["require-context-hook"]
    }
  }
}
```

**Comment by isotopeee** [comment]
Try to upgrade `@storybook/addon-storyshots` to `^4.0.0-alpha.16`.

**Comment by mAAdhaTTah** [comment]
I'm experiencing this issue on `alpha.20`.

**Comment by igor-dv** [comment]
Better have all the SB deps ofvthe same version. Do you @mAAdhaTTah. ?

**Comment by daviscabral** [comment]
I was also getting that error, but after updating it changed to the error below:

```
 FAIL  src/storyshots.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'getElementById' of undefined

      at Object.<anonymous> (node_modules/@storybook/react/dist/client/preview/render.js:42:31)
      at Object.<anonymous> (node_modules/@storybook/react/dist/client/preview/index.js:14:38)
      at Object.<anonymous> (node_modules/@storybook/react/dist/client/index.js:49:16)
```

This is the storyshot file:
```js
import initStoryshots from '@storybook/addon-storyshots'

initStoryshots()
```

And the config.js
```js
import React from 'react'
import { configure, addDecorator } from '@storybook/react'
import { withConsole } from '@storybook/addon-console'
import { withTests } from '@storybook/addon-jest'
import { host } from 'storybook-host'
import results from '../.jest-test-results.json'
import '../src/index.css'

addDecorator((storyFn, context) => withConsole()(storyFn)(context))
addDecorator(withTests({ results }))
addDecorator(host({
    align: 'center top',
    height: '80%',
    width: '80%',
  }))

const req = require.context('components', true, /.stories.js$/)

function loadStories() {
  req.keys().forEach((filename) => req(filename))
}

configure(loadStories, module)
```

These are the versions used by the project:
```js
  "devDependencies": {
    "@babel/core": "^7.0.1",
    "@babel/runtime": "^7.0.0",
    "@storybook/addon-actions": "^4.0.0-alpha.21",
    "@storybook/addon-console": "^1.0.4",
    "@storybook/addon-jest": "^4.0.0-alpha.21",
    "@storybook/addon-links": "^4.0.0-alpha.21",
    "@storybook/addon-storyshots": "^4.0.0-alpha.21",
    "@storybook/addon-viewport": "^4.0.0-alpha.21",
    "@storybook/addons": "^4.0.0-alpha.21",
    "@storybook/react": "^4.0.0-alpha.21",
    "babel-core": "^7.0.0-bridge.0",
    "babel-loader": "^8.0.2",
    "babel-plugin-require-context-hook": "^1.0.0",
    "babel-preset-react": "^7.0.0-beta.3",
    "emotion": "^9.2.8",
    "enzyme": "^3.6.0",
    "enzyme-adapter-react-16": "^1.5.0",
    "enzyme-to-json": "^3.3.4",
    "eslint": "^5.5.0",
    "eslint-config-universe": "^2.0.0-alpha.0",
    "file": "^0.2.2",
    "flow-bin": "^0.80.0",
    "husky": "^1.0.0-rc.14",
    "jest": "^22.0.0",
    "jest-enzyme": "^6.0.4",
    "jest-expo": "30.0.0",
    "jest-localstorage-mock": "^2.2.0",
    "prettier": "^1.14.2",
    "react-error-overlay": "^4.0.1",
    "react-test-renderer": "^16.5.0",
    "require-context": "bojidar-bg/require-context",
    "storybook-host": "^5.0.0",
    "stylus-supremacy": "^2.12.3",
    "system": "^2.0.1"
  },
```

custom .babelrc that is inside the `.storybook` folder:
```json
{
  "presets": ["react-app"],
  "env": {
    "test": {
      "plugins": ["require-context-hook"]
    }
  }
}
```

And the `setupTest.js`:
```js
import React from 'react'
import enzyme from 'enzyme'
import Adapter from 'enzyme-adapter-react-16'
import 'jest-enzyme'
import 'jest-localstorage-mock'
import renderer from 'react-test-renderer'

import registerRequireContextHook from 'babel-plugin-require-context-hook/register'
registerRequireContextHook()

process.env.NODE_ENV = 'development'

enzyme.configure({ adapter: new Adapter() })

global.window = global;
window.addEventListener = () => {};
window.requestAnimationFrame = () => {
  throw new Error('requestAnimationFrame is not supported in Node');
};
```


BTW, it's an `CRA` that was not ejected.

**Comment by igor-dv** [comment]
The line your error is coming from is this:

```js
var rootEl = _global.document.getElementById('root');
```

Looks like you don't have a document on a `window`... 

Also, this line in your `setupTest.js` looks suspicious:
```js
global.window = global;
```

**Comment by mAAdhaTTah** [comment]
Yeah, it was a version mismatch issue in this case.

**Comment by adamchenwei** [comment]
@mAAdhaTTah sorry, would you elaborate what version is worng and what it should be? I am also still having the same issue

@igor-dv maybe should leave it open?

**Comment by mAAdhaTTah** [comment]
All of your `@storybook` packages need to be on the same rc version. You have `"@storybook/addon-storyshots": "^3.4.11",` which is what's causing your issue.

**Comment by adamchenwei** [comment]
fixed thanks! @mAAdhaTTah
