### ISSUE TITLE
Cannot build v4.0.0-alpha.17: missing @babel dependency

### ISSUE THREAD

**Issue by alexkrautmann** [storybooks/storybook#4071]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

After upgrading all storybook deps to the latest alpha (v4.0.0-alpha.17), `start-storybook` fails with with an error about missing `@babel/plugin-proposal-class-properties` in @storybook/core.

### Steps to reproduce

1) install storybook deps in project
2) run `start-storybook -p 6006 -c .storybook`

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/addon-a11y@4.0.0-alpha.17
- @storybook/addon-backgrounds@4.0.0-alpha.17
- @storybook/addon-info@4.0.0-alpha.17
- @storybook/addon-knobs@4.0.0-alpha.17
- @storybook/addon-options@4.0.0-alpha.17
- @storybook/addon-storysource@4.0.0-alpha.17
- @storybook/addon-viewport@4.0.0-alpha.17
- @storybook/react@4.0.0-alpha.17

### Affected platforms 

macos

### Screenshots / Screencast / Code Snippets (Optional)

```bash
14:45 $ yarn storybook
yarn run v1.9.2
$ start-storybook -p 6006 -c .storybook
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module '@babel/plugin-proposal-class-properties'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.resolve (internal/modules/cjs/helpers.js:18:19)
    at Object.<anonymous> (/Users/alexkrautmann/repos/github.com/alexkrautmann/lerna-workspaces-typescript/node_modules/@storybook/core/dist/server/config/babel.js:13:117)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
error Command failed with exit code 1.
```

**Comment by shilman** [comment]
Released a fix. Please give it a try!

https://github.com/storybooks/storybook/releases/tag/v4.0.0-alpha.18

**Comment by alexkrautmann** [comment]
I installed all storybook deps to alpha.18,and now get a different error running storybook.

Note this error is from
```
ERROR in multi ./node_modules/@storybook/core/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/server/config/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true
Module not found: Error: Can't resolve 'babel-loader' in '/Users/alex/repos/github.com/alexkrautmann/lerna-workspaces-typescript'
 @ multi ./node_modules/@storybook/core/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/server/config/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true iframe[2]

ERROR in multi ./.storybook/addons.js ./node_modules/@storybook/core/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/client/manager/index.js
Module not found: Error: Can't resolve 'babel-loader' in '/Users/alex/repos/github.com/alexkrautmann/lerna-workspaces-typescript'
 @ multi ./.storybook/addons.js ./node_modules/@storybook/core/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/client/manager/index.js manager[0]
ℹ ｢wdm｣: Failed to compile.

```

I did the following:

- pulled down storybook repo
- installed babel-loader@7.x (babel 6) in core and workspace
- yarn install and bootstrap --all
- linked every storybook dep I use into my project
- ran dev in storybook project
- ran my storybook

```
ERROR in multi /Users/alex/repos/github.com/storybook/lib/core/dist/server/config/polyfills.js /Users/alex/repos/github.com/storybook/lib/core/dist/server/config/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true
Module not found: Error: Can't resolve 'babel-loader' in '/Users/alex/repos/github.com/alexkrautmann/lerna-workspaces-typescript'
 @ multi /Users/alex/repos/github.com/storybook/lib/core/dist/server/config/polyfills.js /Users/alex/repos/github.com/storybook/lib/core/dist/server/config/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true iframe[2]

ERROR in multi ./.storybook/addons.js /Users/alex/repos/github.com/storybook/lib/core/dist/server/config/polyfills.js /Users/alex/repos/github.com/storybook/lib/core/dist/client/manager/index.js
Module not found: Error: Can't resolve 'babel-loader' in '/Users/alex/repos/github.com/alexkrautmann/lerna-workspaces-typescript'
 @ multi ./.storybook/addons.js /Users/alex/repos/github.com/storybook/lib/core/dist/server/config/polyfills.js /Users/alex/repos/github.com/storybook/lib/core/dist/client/manager/index.js manager[0]
ℹ ｢wdm｣: Failed to compile.
```

I can see in this error that I am properly linked. 

I then tried installing babel-loader@8.0.0-beta.6 (babel 7) in storybook lerna and core and get:

```
ERROR in ./.storybook/config.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
    at throwVersionError (/Users/alex/repos/github.com/storybook/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
    at Object.assertVersion (/Users/alex/repos/github.com/storybook/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
    at _default (/Users/alex/repos/github.com/storybook/node_modules/@babel/plugin-proposal-class-properties/lib/index.js:81:7)
    at /Users/alex/repos/github.com/storybook/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at Function.memoisePluginContainer (/Users/alex/repos/github.com/alexkrautmann/lerna-workspaces-typescript/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/Users/alex/repos/github.com/alexkrautmann/lerna-workspaces-typescript/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /Users/alex/repos/github.com/alexkrautmann/lerna-workspaces-typescript/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/alex/repos/github.com/alexkrautmann/lerna-workspaces-typescript/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/alex/repos/github.com/alexkrautmann/lerna-workspaces-typescript/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/alex/repos/github.com/alexkrautmann/lerna-workspaces-typescript/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/alex/repos/github.com/alexkrautmann/lerna-workspaces-typescript/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/alex/repos/github.com/alexkrautmann/lerna-workspaces-typescript/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/alex/repos/github.com/alexkrautmann/lerna-workspaces-typescript/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/alex/repos/github.com/alexkrautmann/lerna-workspaces-typescript/node_modules/babel-loader/lib/index.js:50:20)
    at /Users/alex/repos/github.com/alexkrautmann/lerna-workspaces-typescript/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/Users/alex/repos/github.com/alexkrautmann/lerna-workspaces-typescript/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:434:13)
 @ multi /Users/alex/repos/github.com/storybook/lib/core/dist/server/config/polyfills.js /Users/alex/repos/github.com/storybook/lib/core/dist/server/config/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true iframe[2]

ERROR in ./.storybook/addons.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
    at throwVersionError (/Users/alex/repos/github.com/storybook/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
    at Object.assertVersion (/Users/alex/repos/github.com/storybook/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
    at _default (/Users/alex/repos/github.com/storybook/node_modules/@babel/plugin-proposal-class-properties/lib/index.js:81:7)
    at /Users/alex/repos/github.com/storybook/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at Function.memoisePluginContainer (/Users/alex/repos/github.com/alexkrautmann/lerna-workspaces-typescript/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/Users/alex/repos/github.com/alexkrautmann/lerna-workspaces-typescript/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /Users/alex/repos/github.com/alexkrautmann/lerna-workspaces-typescript/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/alex/repos/github.com/alexkrautmann/lerna-workspaces-typescript/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/alex/repos/github.com/alexkrautmann/lerna-workspaces-typescript/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/alex/repos/github.com/alexkrautmann/lerna-workspaces-typescript/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/alex/repos/github.com/alexkrautmann/lerna-workspaces-typescript/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/alex/repos/github.com/alexkrautmann/lerna-workspaces-typescript/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/alex/repos/github.com/alexkrautmann/lerna-workspaces-typescript/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/alex/repos/github.com/alexkrautmann/lerna-workspaces-typescript/node_modules/babel-loader/lib/index.js:50:20)
    at /Users/alex/repos/github.com/alexkrautmann/lerna-workspaces-typescript/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/Users/alex/repos/github.com/alexkrautmann/lerna-workspaces-typescript/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:434:13)
 @ multi ./.storybook/addons.js /Users/alex/repos/github.com/storybook/lib/core/dist/server/config/polyfills.js /Users/alex/repos/github.com/storybook/lib/core/dist/client/manager/index.js manager[0]
```

This is a typescript project, so I don't want to have babel or babel loader in my project. I would expect these deps to be handled in storybook.

Just to test it out I installed @babel/core and babel-loader@8.0.0-beta.6 in my typescript project and storybook builds and runs fine. 

Everything worked for me on storybook alpha 16.

**Comment by Hypnosphi** [comment]
Do you have a `.babelrc` file?

**Comment by Hypnosphi** [comment]
> This is a typescript project, so I don't want to have babel or babel loader in my project. I would expect these deps to be handled in storybook.

We need to support different versions of babel so having `babel-loader` as a peer dependency is an inevitable evil

**Comment by alexkrautmann** [comment]
> Do you have a .babelrc file?

I have a `.babelrc` under `.storybook/`.

> We need to support different versions of babel so having babel-loader as a peer dependency is an inevitable evil

The thing is, I don't use `babel-loader` anywhere in the project proper. I do have `babel-plugin-require-context-hook` in my storyshots jest config as well as the mentioned `.storybook/.babelrc`. 

I just looked over alpha.17, which is what caused the peerDep on babel-loader: #3746. Adding the additional `babel-loader` dep isn't the end of the world, but I would prefer it be managed by storybook directly. Thanks for taking the time looking into this and getting in the quick fix over the weekend!

Cheers 🥂

**Comment by alexkrautmann** [comment]
I went ahead and installed alpha.18. It also requires I install @babel/core as I mentioned in a previous message. It really is unfortunate I have to add 2 deps for storybook that I don't actually use in my project. I'm not sure if this truly is a bug or intended, I imagine this changes the barrier of entry to using storybook on existing projects. 

At this point though, it is a different issue.

**Comment by Hypnosphi** [comment]
>  don't use babel-loader anywhere in the project proper.

But we do. And to know which version to use, we need it to be installed on your side. And yes, you also need to install either `babel-core@6` or `@babel/core@7`. This shouldn't be a barrier for newcomers though, as we add those dependencies in `getstorybook` command.

> I have a .babelrc under .storybook/.

How does it look?

**Comment by Hypnosphi** [comment]
Thanks @sregg, https://github.com/storybooks/storybook/pull/4117 should fix it
