### ISSUE TITLE
@storybook/react 4.0.0-alpha.18 Throwing Error

### ISSUE THREAD

**Issue by ritchieanesco** [storybooks/storybook#4085]
If you are reporting a bug or requesting support, start here:

### Bug or support request summary

The latest version of storybook (4.0.0-alpha.18) is breaking the build. So as a temporary solution we have had to roll back to 4.0.0-alpha16.

_Please provide issue details here - What did you expect to happen? What happened instead?_ 

Expected:
Executed the following task and expected the storybook build to complete successfully. 
```
cross-env NODE_ENV=production build-storybook -c source/App/Lib/.storybook -o ClientName/Storybook
```
 Actual:
The storybook is throwing the following exception:
```
[20:44:39]                                                   76% advanced chunk optimization RemoveEmptyChunksPlugin
[20:44:39]              ...acc,
[20:44:39]              ^^^
[20:44:39]SyntaxError: Unexpected token ...
[20:44:39]    at Object.exports.runInThisContext (vm.js:76:16)
[20:44:39]    at Module._compile (module.js:542:28)
[20:44:39]    at Object.Module._extensions..js (module.js:579:10)
[20:44:39]    at Module.load (module.js:487:32)
[20:44:39]    at tryModuleLoad (module.js:446:12)
[20:44:39]    at Function.Module._load (module.js:438:3)
[20:44:39]    at Module.require (module.js:497:17)
[20:44:39]    at require (internal/module.js:20:19)
[20:44:39]    at Object.<anonymous> (C:\BuildAgent\work\89174915197d6e98\node_modules\@storybook\core\dist\server\config\webpack.config.prod.js:16:57)
[20:44:39]    at Module._compile (module.js:570:32)
```
_Please provide necessary steps for reproduction of this issue. Describe the exact steps a maintainer has to take to make the problem occur. If the problem is non-trivial to reproduce, please link a repository or provide some code snippets._

_(A screencast can be useful for visual bugs, but it is not a substitute for a textual description.)_

### Please specify which version of Storybook and optionally any affected addons that you're running
        "babel-core": "6.26.3",
        "babel-loader": "^7.1.5",
        "@storybook/addon-actions": "3.4.10",
        "@storybook/addon-info": "3.4.10",
        "@storybook/addon-knobs": "3.4.10",
        "@storybook/addon-options": "3.4.10",
        "@storybook/cli": "4.0.0-alpha.18",
        "@storybook/react": "4.0.0-alpha.18"

### Affected platforms 
Node v10.8.0

### Screenshots / Screencast / Code Snippets (Optional)

```
//webpack config
module.exports = {
    module: {
        rules: [
            {
                test: /\.(js|jsx)$/,
                exclude: [/node_modules/],
                loader: 'babel-loader',
                include: [path.resolve(__dirname, '../../../App')]
            },
            {
                test: /\.scss$/,
                loaders: ['style-loader', 'css-loader', 'sass-loader'],
                include: path.resolve(__dirname, '../../../assets/sass')
            },
            {
                test: /\.css$/,
                loaders: ['style-loader', 'css-loader'],
                include: [path.resolve(__dirname, '../../../App')]
            },
            {
                test: /\.(png|jpg|gif|woff|svg|woff2)$/,
                use: [
                    {
                        loader: 'url-loader',
                        options: {
                            limit: 8192,
                            name: '[name]-[hash].[ext]'
                        }
                    }
                ]
            }
        ]
    },
    plugins: [
        new webpack.DefinePlugin({
            ENVIRONMENT: JSON.stringify(environment),
            VERSION: JSON.stringify(version)
        })
    ]
};

//babel config
{
    "presets": [
        "flow",
        "react",
        [
            "env",
            {
                "targets": {
                    "browsers": "last 2 versions"
                },
                "loose": true,
                "modules": false
            }
        ]
    ],
    "plugins": [
        "es6-promise",
        "transform-es2015-template-literals",
        "transform-object-rest-spread",
        "babel-plugin-dynamic-import-node",
        "babel-plugin-transform-decorators-legacy",
        "babel-plugin-transform-class-properties",
        "babel-plugin-transform-es2015-arrow-functions",
        "transform-es2015-modules-commonjs",
        "syntax-dynamic-import"
    ],
    "env": {
        "production": {
            "plugins": ["transform-react-remove-prop-types"]
        }
    }
}
```
End bug report support request - delete the rest below

**Comment by Hypnosphi** [comment]
Do you have any babel config?

**Comment by ritchieanesco** [comment]
@Hypnosphi updated description with babel config.
