### ISSUE TITLE
*Cannot read property 'parent' of undefined* when calling *initStoryshoots()*

### ISSUE THREAD

**Issue by brunoreis** [storybooks/storybook#4102]
I'm getting this error:
```
    TypeError: Cannot read property 'parent' of undefined

      at Object.<anonymous> (node_modules/@storybook/react/dist/client/preview/globals.js:5:20)
      at Object.<anonymous> (node_modules/@storybook/react/dist/client/preview/index.js:10:1)
      at Object.<anonymous> (node_modules/@storybook/react/dist/client/index.js:7:16)
```

when running 

```
initStoryshots(); 
````
in my only jest test

storybook and all addons are @4.0.0-alpha.16

Please let me know if you have any hint of what is be happening. I'll dive deep into it in the next days.

**Comment by brunoreis** [comment]
it's happening when the loader requires @storybook/react: 

```
var storybook = require.requireActual('@storybook/react');
```

**Comment by brunoreis** [comment]
using 
````
var window = require('global/window');
```
fixed this making storyshots work again
before it was like
```
var _global = require('global');
_global.window....
```

**Comment by brunoreis** [comment]
@Hypnosphi, please, I was studying newest commits and this is fixed, right?  
I'm using alpha16 here because I need to evaluate moving to babel 7 with the team.

**Comment by hirumi16489** [comment]
Hello, I have the same exact issue with @4.0.0-alpha.20. Could we please have an update about that ? Is it even possible to use storyshots @4 ?

**Comment by hirumi16489** [comment]
FYI, I found a workaround but I have no idea if it destroys any features, snapshots are generated and testing are working well so far.

Just declare a setupFile in your jest config, then write in it:
`var global = require("global");
var document = require("global/document");

global.window = {};
global.document = document;`

**Comment by igor-dv** [comment]
Did you set `testEnvironment: 'jsdom'` in `jest.config.js` ?

**Comment by brunoreis** [comment]
Hey @igor-dv, that worked fine here. Thanks a lot for alerting on that config. 
In fact "jsdom" is the default option for that config: 
https://jestjs.io/docs/en/configuration.html#testenvironment-string

But in this project I'm working now it was set as "node". Probably because it was copied from a config used to test the server or something like that. 

What do you think about adding a note on this section: https://github.com/storybooks/storybook/tree/release/3.4/addons/storyshots#configure-your-app-for-jest saying something like "Please make you are using 'jsdom' as the testEnvironmnet on your jest config."?

**Comment by Hypnosphi** [comment]
@brunoreis you should be able to use current alpha with Babel 6
