### ISSUE TITLE
Storybook + Typescript (Issue: Requires Babel "^7.0.0-0", but was loaded with "6.26.3")

### ISSUE THREAD

**Issue by reggi** [storybooks/storybook#4177]
I am following the [Typescript](https://storybook.js.org/configurations/typescript-config/) documentation. 

I am using version `^4.0.0-alpha.21` of storybook.

```
    "@storybook/addon-actions": "^4.0.0-alpha.21",
    "@storybook/addon-info": "^4.0.0-alpha.21",
    "@storybook/addon-links": "^4.0.0-alpha.21",
    "@storybook/addons": "^4.0.0-alpha.21",
    "@storybook/react": "^4.0.0-alpha.21",
```

The issue here is that the default webpack config is depending on an old version of `babel-core`, when I install `@babel/core@7.0.1` it is still using `babel-core@6.26.3`. 

```
ERROR in ./.storybook/config.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel. (While processing preset: "/Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/@babel/preset-react/lib/index.js")
    at throwVersionError (/Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
    at Object.assertVersion (/Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
    at _default (/Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/@babel/preset-react/lib/index.js:61:7)
    at /Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at /Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/babel-core/lib/transformation/file/options/option-manager.js:317:46
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/babel-loader/lib/index.js:50:20)
    at /Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
 @ multi ./node_modules/@storybook/core/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/server/config/globals.js ./.storybook/config.js ./node_modules/webpack-hot-middleware/client.js?reload=true iframe[2]
```

```
ERROR in ./.storybook/addons.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel. (While processing preset: "/Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/@babel/preset-react/lib/index.js")
    at throwVersionError (/Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
    at Object.assertVersion (/Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
    at _default (/Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/@babel/preset-react/lib/index.js:61:7)
    at /Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at /Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/babel-core/lib/transformation/file/options/option-manager.js:317:46
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/babel-loader/lib/index.js:50:20)
    at /Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/Users/thomas.reggi/Desktop/git/github.com/alfredclub/admin-portal/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
 @ multi ./.storybook/addons.js ./node_modules/@storybook/core/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/client/manager/index.js manager[0]
```

**Comment by igor-dv** [comment]
You should also install `babel-loader` **8**.

**Comment by pksunkara** [comment]
Might be related to https://github.com/storybooks/storybook/issues/4192

**Comment by mrmartineau** [comment]
I am also seeing the similar errors when using version `^4.0.0-alpha.22` of the various storybook packages..

```sh
info @storybook/react v4.0.0-alpha.22
info
info => Loading presets
info => Loading custom addons config.
info => Loading custom webpack config (full-control mode).
 10% building modules 2/2 modules 0 activeℹ ｢wdm｣: wait until bundle finished:
webpack built 8a5184064a2b074299c8 in 8444ms
✖ ｢wdm｣: Hash: 8a5184064a2b074299c8
Version: webpack 4.19.1
Time: 8444ms
Built at: 09/21/2018 12:27:33 PM
                       Asset       Size   Chunks                    Chunk Names
     static/iframe.bundle.js    557 KiB   iframe  [emitted]  [big]  iframe
    static/manager.bundle.js   2.86 MiB  manager  [emitted]  [big]  manager
                 iframe.html   61.6 KiB           [emitted]
                  index.html  881 bytes           [emitted]
 static/iframe.bundle.js.map    565 KiB   iframe  [emitted]         iframe
static/manager.bundle.js.map   3.03 MiB  manager  [emitted]         manager
Entrypoint iframe [big] = static/iframe.bundle.js static/iframe.bundle.js.map
Entrypoint manager [big] = static/manager.bundle.js static/manager.bundle.js.map
[./.storybook/addons.js] 1.33 KiB {manager} [built] [failed] [1 error]
[./.storybook/config.js] 1.33 KiB {iframe} [built] [failed] [1 error]
[./node_modules/@storybook/core/dist/client/manager/index.js] 366 bytes {manager} [built]
[./node_modules/@storybook/core/dist/client/manager/provider.js] 3.15 KiB {manager} [built]
[./node_modules/@storybook/core/dist/server/config/globals.js] 93 bytes {iframe} [built]
[./node_modules/@storybook/core/dist/server/config/polyfills.js] 113 bytes {iframe} {manager} [built]
[./node_modules/@storybook/ui/dist/index.js] 2.19 KiB {manager} [built]
[./node_modules/global/window.js] 232 bytes {iframe} {manager} [built]
[./node_modules/webpack-hot-middleware/client-overlay.js] (webpack)-hot-middleware/client-overlay.js 2.16 KiB {iframe} [built]
[./node_modules/webpack-hot-middleware/client.js?reload=true] (webpack)-hot-middleware/client.js?reload=true 7.59 KiB {iframe} [built]
[./node_modules/webpack-hot-middleware/node_modules/strip-ansi/index.js] (webpack)-hot-middleware/node_modules/strip-ansi/index.js 161 bytes {iframe} [built]
[./node_modules/webpack-hot-middleware/process-update.js] (webpack)-hot-middleware/process-update.js 4.26 KiB {iframe} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {iframe} {manager} [built]
[0] multi ./node_modules/@storybook/core/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/server/config/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true 64 bytes {iframe} [built]
[1] multi ./.storybook/addons.js ./node_modules/@storybook/core/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/client/manager/index.js 52 bytes {manager} [built]
    + 728 hidden modules

ERROR in ./.storybook/addons.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/zander/app/node_modules/babel-preset-react/lib/index.js
    at createDescriptor (/Users/zander/app/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
    at items.map (/Users/zander/app/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/zander/app/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/Users/zander/app/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at presets (/Users/zander/app/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
    at mergeChainOpts (/Users/zander/app/node_modules/@babel/core/lib/config/config-chain.js:315:26)
    at /Users/zander/app/node_modules/@babel/core/lib/config/config-chain.js:278:7
    at buildRootChain (/Users/zander/app/node_modules/@babel/core/lib/config/config-chain.js:118:22)
    at loadPrivatePartialConfig (/Users/zander/app/node_modules/@babel/core/lib/config/partial.js:85:55)
 @ multi ./.storybook/addons.js ./node_modules/@storybook/core/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/client/manager/index.js manager[0]

ERROR in ./.storybook/config.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/zander/app/node_modules/babel-preset-react/lib/index.js
    at createDescriptor (/Users/zander/app/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
    at items.map (/Users/zander/app/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/zander/app/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/Users/zander/app/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at presets (/Users/zander/app/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
    at mergeChainOpts (/Users/zander/app/node_modules/@babel/core/lib/config/config-chain.js:315:26)
    at /Users/zander/app/node_modules/@babel/core/lib/config/config-chain.js:278:7
    at buildRootChain (/Users/zander/app/node_modules/@babel/core/lib/config/config-chain.js:118:22)
    at loadPrivatePartialConfig (/Users/zander/app/node_modules/@babel/core/lib/config/partial.js:85:55)
 @ multi ./node_modules/@storybook/core/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/server/config/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true iframe[2]
ℹ ｢wdm｣: Failed to compile.
```

here's my `devDependencies`:

```json
{
  "devDependencies": {
    "@babel/core": "^7.1.0",
    "@storybook/addon-a11y": "4.0.0-alpha.22",
    "@storybook/addon-actions": "4.0.0-alpha.22",
    "@storybook/addon-backgrounds": "4.0.0-alpha.22",
    "@storybook/addon-knobs": "4.0.0-alpha.22",
    "@storybook/addon-links": "4.0.0-alpha.22",
    "@storybook/addon-options": "4.0.0-alpha.22",
    "@storybook/addons": "4.0.0-alpha.22",
    "@storybook/react": "4.0.0-alpha.22",
    "@types/jest": "^23.3.1",
    "@types/react": "^16.4.11",
    "@types/storybook__addon-a11y": "^3.3.1",
    "@types/storybook__addon-actions": "^3.4.1",
    "@types/storybook__addon-info": "^3.4.1",
    "@types/storybook__addon-knobs": "^3.4.1",
    "@types/storybook__react": "^3.0.9",
    "awesome-typescript-loader": "^5.2.0",
    "babel-loader": "^8.0.2",
    "babel-plugin-external-helpers": "^6.22.0",
    "babel-plugin-styled-components": "1.5.1",
    "babel-plugin-transform-class-properties": "6.24.1",
    "babel-plugin-transform-es2015-modules-commonjs": "6.26.2",
    "babel-plugin-transform-object-rest-spread": "6.26.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "6.24.1",
    "chromatism": "3.0.0",
    "cross-env": "5.2.0",
    "depdoc": "1.0.3",
    "husky": "1.0.0-rc.13",
    "jest": "^23.5.0",
    "jest-dom": "1.10.0",
    "jest-junit": "5.1.0",
    "jest-styled-components": "^6.2.0",
    "lint-staged": "^7.3.0",
    "precise-commits": "1.0.2",
    "prettier": "1.13.7",
    "react": "^16.4.2",
    "react-chromatic": "0.8.4",
    "react-dom": "^16.4.2",
    "react-testing-library": "4.1.3",
    "release-it": "7.4.7",
    "rollup": "^0.63.2",
    "rollup-plugin-auto-external": "1.2.0",
    "rollup-plugin-babel": "^3.0.6",
    "rollup-plugin-commonjs": "^9.1.3",
    "rollup-plugin-jsx": "1.0.3",
    "rollup-plugin-node-resolve": "^3.3.0",
    "rollup-plugin-typescript2": "^0.16.1",
    "size-limit": "0.18.5",
    "storybook-addon-jsx": "^5.4.0",
    "storybook-readme": "^4.0.0-beta1",
    "styled-components": "^3.4.2",
    "ts-jest": "^23.1.4",
    "tslint": "^5.11.0",
    "tslint-config-airbnb": "^5.9.2",
    "tslint-config-prettier": "^1.14.0",
    "tslint-plugin-prettier": "^1.3.0",
    "tslint-react": "^3.6.0",
    "typescript": "^3.0.1"
  }
}
```

**Comment by mrmartineau** [comment]
thanks @reggi, I just tried it with babel-bridge to no avail:

this line was added to my `devDependencies`:

```json
"babel-core": "^7.0.0-bridge.0",
```

It's this error that consfuses me:

```
Error: => Create a storybook config file in "./.storybook/config.{ext}".
```

Why would it say that when there is a config in that directory??

**Comment by igor-dv** [comment]
@reggi, actually it's not a hacky wat to solve it. If you still want to use babel 6, you have to do this with a bridge. 

@mrmartineau, is this a full error? can you maybe print script it ?

**Comment by mrmartineau** [comment]
@igor-dv no it wasn't the full error. I'll get the full error soon. Cheers
