### ISSUE TITLE
getstorybook installed wrong version of webpack?

### ISSUE THREAD

**Issue by westandy** [storybooks/storybook#4301]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary
I have a newly built angular 6 project.  I then installed getstorybook and ran it in my project.  All is well so far.  I then run `npm run storybook` and I get the following error, which has been reported in other issues.  However, the solution I have seen is to upgrade storybook to an alpha version.  But I'm using @storybook/angular.  Can I add alpha and make it work?  (Sorry, I'm new to Angular and find it very difficult to figure out what is going on.  With React, I felt I had more visibility into my projects.)

Any help is appreciated!

```
f:\www\console-lite\node_modules\webpack\lib\DefinePlugin.js:93
                compiler.hooks.compilation.tap(
                               ^

TypeError: Cannot read property 'compilation' of undefined
    at DefinePlugin.apply (f:\www\console-lite\node_modules\webpack\lib\DefinePlugin.js:93:18)
    at Compiler.apply (f:\www\console-lite\node_modules\@storybook\core\node_modules\tapable\lib\Tapable.js:375:16)
    at webpack (f:\www\console-lite\node_modules\@storybook\core\node_modules\webpack\lib\webpack.js:33:19)
    at exports.default (f:\www\console-lite\node_modules\@storybook\core\dist\server\middleware.js:29:40)
    at buildDev (f:\www\console-lite\node_modules\@storybook\core\dist\server\build-dev.js:163:36)
    at Object.<anonymous> (f:\www\console-lite\node_modules\@storybook\react\dist\server\index.js:23:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (f:\www\console-lite\node_modules\@storybook\react\bin\index.js:3:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
```
### Steps to reproduce

_Please provide necessary steps for reproduction of this issue. Describe the exact steps a maintainer has to take to make the problem occur. If the problem is non-trivial to reproduce, please link a repository or provide some code snippets._

_(A screencast can be useful for visual bugs, but it is not a substitute for a textual description.)_

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react x.x.x
- @storybook/addon-something x.x.x

### Affected platforms 

- _If UI related, please indicate browser, OS, and version_
- _If dependency related, please include relevant version numbers_
- _If developer tooling related, please include the platform information_

### Screenshots / Screencast / Code Snippets (Optional)

```js
// code here
```
End bug report support request - delete the rest below

If you are creating a issue to track work to be completed, start here:
### Work summary

_Please provide a description of the work to be completed here - Include some context as to why something needs to be done and link any related tickets._ 

### Where to start

_Please list the file(s) a contributor needs to figure out where to start work and include any docs or tutorials that may be applicable._

### Acceptance criteria

_Please include a checklist of the requirements necessary to close this ticket. The work should be narrowly scoped and limited to a few hours worth by an experienced developer at the most._

### Who to contact

_Add yourself and/or people who are familiar with the code changes and requirements. These people should be able to review the completed code._
End work issue - please tag this issue with the correct status and type labels

**Comment by westandy** [comment]
I think I may have figured it out.  Just upgrade my `@storybook/angular` to v4.0.0-alpha.  I was looking in all the wrong places... should had just read the ReadMe.md
