### ISSUE TITLE
start-storybook fails with cryptic error inside a docker image

### ISSUE THREAD

**Issue by marvinhagemeister** [storybooks/storybook#4342]
### Bug Summary

When the command `start-storybook` is run inside a docker container the command fails with an `UnhandledPromiseRejection` warning:

```bash
(node:26) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/home/node/app/node_modules/opn/index.js:85:13)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)
(node:26) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 62)
(node:26) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Putting a `console.trace()` inside the `opn` module leads to this stack trace:

```
Trace
    at module.exports (/home/node/app/node_modules/opn/index.js:76:9)
    at _callee$ (/home/node/app/node_modules/@storybook/core/dist/server/build-dev.js:230:32)
    at tryCatch (/home/node/app/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/node/app/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/home/node/app/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/home/node/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/node/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

With this trace we could narrow the issue down to this line in `build-dev.js` https://github.com/storybooks/storybook/blob/bda1dc00205cfc2b2a3b077bf748d0e39f6aef3c/lib/core/src/server/build-dev.js#L163

which is missing a `.catch()`-handler. At this line storybook tries to open the newly created server with the default program associated to urls via the system.

_Please provide issue details here - What did you expect to happen? What happened instead?_ 

Instead of throwing an `UnhandledPromiseRejection` it would be amazing to print a human readable message. Something like:

```
Could not open ${url} inside a browser. If you're running this command inside a
docker container or on a CI, you need to pass the '--ci' flag to prevent opening a
browser by default.
```

### Steps to reproduce

1. Create empty storybook project
2. Put it inside a standard node docker image
3. execute `start-storybook` inside the running container

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 4.0.0-alpha.24
- @storybook/addon-something 4.0.0-alpha.24

### Affected platforms 

- Docker node 10.11.0 (both the default and alpine variant)

### Work summary

Add the missing `.catch()`-handler and print a nice human readable error message with an action what can be done about this.

### Where to start

_Please list the file(s) a contributor needs to figure out where to start work and include any docs or tutorials that may be applicable._

https://github.com/storybooks/storybook/blob/bda1dc00205cfc2b2a3b077bf748d0e39f6aef3c/lib/core/src/server/build-dev.js#L163

### Acceptance criteria

_Please include a checklist of the requirements necessary to close this ticket. The work should be narrowly scoped and limited to a few hours worth by an experienced developer at the most._

- [ ] Added a `.catch()`-handler
- [ ] Added a nice error message

### Who to contact

Just ping me here on github.

**Comment by gabrielcsapo** [comment]
@marvinhagemeister hi! Would you be able to try and run it with the argument `--ci` and see if that remedies the issue?

**Comment by gabrielcsapo** [comment]
@marvinhagemeister I think this would be a great addition!

**Comment by gabrielcsapo** [comment]
I opened a PR to fix this behavior
