### ISSUE TITLE
Missing dependency to module uuid

### ISSUE THREAD

**Issue by bm-stschneider** [storybooks/storybook#4662]
**Describe the bug**
There seems to be a dependency missing for the cli

**To Reproduce**
run `npx -p @storybook/cli sb init -t html`
run `npm run storybook`

**Expected behavior**
`npm run storybook` should run without problems after initial init

```log
module.js:557
    throw err;
    ^

Error: Cannot find module 'uuid/v4'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/node_modules/webpack-log/src/index.js:9:14)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/node_modules/webpack-dev-middleware/lib/context.js:3:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Exit status 1
npm ERR!
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by igor-dv** [comment]
I can't reproduce this.,. Everything works for me on a fresh install 🤷‍♂️

**Comment by bm-stschneider** [comment]
I could recreate the scenario by running
`npx -p @storybook/cli sb init`
`npm run storybook`
I have still the same problem.

**Comment by igor-dv** [comment]
Did you use it with `-t html` ?

**Comment by bm-stschneider** [comment]
ha, maybe it was that then. I'll check that.

**Comment by bm-stschneider** [comment]
but wait, I selected HTML manually from the menu

**Comment by igor-dv** [comment]
That's strange. `html-loader` is a direct dep of the `@storybook/html`. It should be installed. And it indeed installed for me.

**Comment by igor-dv** [comment]
I mixed up this issue with #4697 😅 But can't reproduce anyway
