### ISSUE TITLE
Web view is broken with RN 0.57

### ISSUE THREAD

**Issue by maxkomarychev** [storybooks/storybook#4852]
`app/react-native/package.json` bring babel 6.x dependencies which conflict with babel 7.x required by react-native 0.57. More speifically: `babel-preset-react` is installed because of storybook while my `package.json` requires `@babel/preset-react: "^7.0.0"`:

```
$ yarn why babel-preset-react
yarn why v1.10.1
[1/4] 🤔  Why do we have the module "babel-preset-react"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "babel-preset-react@6.24.1"
info Reasons this module exists
   - "@storybook#react-native" depends on it
   - Hoisted from "@storybook#react-native#babel-preset-react"
info Disk size without dependencies: "20MB"
info Disk size with unique dependencies: "140MB"
info Disk size with transitive dependencies: "11.43GB"
info Number of shared dependencies: 15
✨  Done in 1.59s.
```

Does anyone know how to force babel 7 to be used or any other way to make it work together with rn 0.57?

**Describe the bug**
Storybook webview and addons are not usable when rn57 is used.

**To Reproduce**
1. do clean installation of storybook with rn57
2. add some addons 
here's my `addons.js` for example:
```
import '@storybook/react-native/addons'
import '@storybook/addon-knobs/register'
import 'storybook-usage/register'
import '@storybook/addon-actions/register'
import '@storybook/addon-notes/register'
```
3. start webview with `storybook start`
4. observe error in cli:

```
$ yarn storybook
yarn run v1.10.1
$ storybook start
=> Loading custom addons config.
=> Using default webpack setup based on "Create React App".

React Native Storybook started on => http://localhost:7007/

webpack built 9ae038869fc04e564bc7 in 2744ms
✖ ｢wdm｣: Hash: 9ae038869fc04e564bc7
Version: webpack 4.26.1
Time: 2744ms
Built at: 2018-11-26 10:36:51
                   Asset       Size   Chunks             Chunk Names
              index.html  698 bytes           [emitted]
static/manager.bundle.js   6.81 MiB  manager  [emitted]  manager
Entrypoint manager = static/manager.bundle.js
[0] multi ./storybook/addons.js ./node_modules/@storybook/react-native/dist/manager/index.js 40 bytes {manager} [built]
[./node_modules/@babel/runtime/helpers/classCallCheck.js] 196 bytes {manager} [built]
[./node_modules/@babel/runtime/helpers/createClass.js] 596 bytes {manager} [built]
[./node_modules/@babel/runtime/helpers/getPrototypeOf.js] 267 bytes {manager} [built]
[./node_modules/@babel/runtime/helpers/inherits.js] 505 bytes {manager} [built]
[./node_modules/@babel/runtime/helpers/interopRequireDefault.js] 145 bytes {manager} [built]
[./node_modules/@babel/runtime/helpers/objectSpread.js] 623 bytes {manager} [built]
[./node_modules/@babel/runtime/helpers/possibleConstructorReturn.js] 343 bytes {manager} [built]
[./node_modules/@storybook/channel-websocket/dist/index.js] 2.55 KiB {manager} [built]
[./node_modules/@storybook/core-events/index.js] 493 bytes {manager} [built]
[./node_modules/@storybook/react-native/dist/manager/index.js] 457 bytes {manager} [built]
[./node_modules/@storybook/react-native/dist/manager/provider.js] 3.96 KiB {manager} [built]
[./node_modules/@storybook/ui/dist/index.js] 2.19 KiB {manager} [built]
[./node_modules/global/window.js] 232 bytes {manager} [built]
[./storybook/addons.js] 2.07 KiB {manager} [built] [failed] [1 error]
    + 792 hidden modules

ERROR in ./storybook/addons.js
Module build failed (from ./node_modules/@storybook/react-native/node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/user/dev/amazingproject/amazingprojectreactnative/node_modules/babel-preset-react/lib/index.js
    at createDescriptor (/Users/user/dev/amazingproject/amazingprojectreactnative/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
    at items.map (/Users/user/dev/amazingproject/amazingprojectreactnative/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/user/dev/amazingproject/amazingprojectreactnative/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/Users/user/dev/amazingproject/amazingprojectreactnative/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at passPerPreset (/Users/user/dev/amazingproject/amazingprojectreactnative/node_modules/@babel/core/lib/config/config-descriptors.js:58:96)
    at cachedFunction (/Users/user/dev/amazingproject/amazingprojectreactnative/node_modules/@babel/core/lib/config/caching.js:33:19)
    at presets.presets (/Users/user/dev/amazingproject/amazingprojectreactnative/node_modules/@babel/core/lib/config/config-descriptors.js:29:84)
    at mergeChainOpts (/Users/user/dev/amazingproject/amazingprojectreactnative/node_modules/@babel/core/lib/config/config-chain.js:315:26)
    at /Users/user/dev/amazingproject/amazingprojectreactnative/node_modules/@babel/core/lib/config/config-chain.js:278:7
    at buildRootChain (/Users/user/dev/amazingproject/amazingprojectreactnative/node_modules/@babel/core/lib/config/config-chain.js:68:29)
    at loadPrivatePartialConfig (/Users/user/dev/amazingproject/amazingprojectreactnative/node_modules/@babel/core/lib/config/partial.js:85:55)
    at Object.loadPartialConfig (/Users/user/dev/amazingproject/amazingprojectreactnative/node_modules/@babel/core/lib/config/partial.js:110:18)
    at Object.<anonymous> (/Users/user/dev/amazingproject/amazingprojectreactnative/node_modules/@storybook/react-native/node_modules/babel-loader/lib/index.js:140:26)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/user/dev/amazingproject/amazingprojectreactnative/node_modules/@storybook/react-native/node_modules/babel-loader/lib/index.js:3:103)
 @ multi ./storybook/addons.js ./node_modules/@storybook/react-native/dist/manager/index.js manager[0]
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  1.39 MiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core/src/server/templates/index.ejs] 1.65 KiB {HtmlWebpackPlugin_0} [built]
    [./node_modules/html-webpack-plugin/node_modules/lodash/lodash.js] 527 KiB {HtmlWebpackPlugin_0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {HtmlWebpackPlugin_0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 519 bytes {HtmlWebpackPlugin_0} [built]
ℹ ｢wdm｣: Failed to compile.
^C

```

also exception in js console in webview:

```
Uncaught Error: Module build failed (from ./node_modules/@storybook/react-native/node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/user/dev/amazingproject/amazingprojectreactnative/node_modules/babel-preset-react/lib/index.js
   ```

**Expected behavior**
Webview should work

**Screenshots**

**System:**
 - OS: os x high sierra
 - Device: mac book pro
 - Browser: chrome/any
 - Framework: react-native
 - Addons: knobs, actions, notes
 - Version: 4.0.8

**Additional context**

**Comment by maxkomarychev** [comment]
relevant issue: #4011

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.7 containing PR #4942 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.
