### ISSUE TITLE
new text('name', value) not correctly passing values

### ISSUE THREAD

**Issue by StevenFewster** [storybooks/storybook#4871]
Using knobs with @storybook/angular, passing a simple "text" through to my component, it receives an empty text object.

### To Reproduce

```
stories.addDecorator(
    moduleMetadata({
      imports: [
        CommonModule,
        RouterModule.forRoot([], { initialNavigation: 'enabled' }),
        LayoutModule
      ],
      providers: [{provide: APP_BASE_HREF, useValue: '/'}]
    }),
  );
  stories.addDecorator(withKnobs)
  stories.add('default', () => {
    
    const current = 'DEV';
    const testItem = new text('testItem', 'Test Item');
    console.log(testItem);
// NB: this prints as:
// text: {}
    const environmentList = [
        { name: 'PROD', url: '/' },
        { name: 'QA', url: '/' },
        { name: 'DEV', url: '/' }
      ];

    return {
      template: `<app-environment-picker [current]="current" [environmentList]="environmentList"></app-environment-picker>`,
      props: { 
        current: new text('current', current),
        environmentList: new object('environmentList', environmentList)
      },
    };
  });
```

### Expected behavior
Expect a string to be passed to the current attribute and for that string to be 'DEV'

### Details
```
Angular CLI: 7.0.4
Node: 10.13.0
OS: win32 x64
Angular: 7.0.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.4
@angular-devkit/build-angular     0.10.4
@angular-devkit/build-optimizer   0.10.4
@angular-devkit/build-webpack     0.10.4
@angular-devkit/core              7.0.4
@angular-devkit/schematics        7.0.4
@angular/cli                      7.0.4
@ngtools/webpack                  7.0.4
@schematics/angular               7.0.4
@schematics/update                0.10.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1
```

Also worth noting, projects are part of an Nx monorepo

**Comment by StevenFewster** [comment]
Addendum: 
digging in to the constructor on the prototype of the object `testItem` above, I get this:

`Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.remoteFunction (<anonymous>:2:14) at http://localhost:6006/static/iframe.bundle.js:398259:5 at http://localhost:6006/static/iframe.bundle.js:96770:16 at http://localhost:6006/static/iframe.bundle.js:95754:17 at http://localhost:6006/static/iframe.bundle.js:96769:14 at http://localhost:6006/static/iframe.bundle.js:96770:16 at wrapper (http://localhost:6006/static/iframe.bundle.js:94844:12) at http://localhost:6006/static/iframe.bundle.js:95409:14 at http://localhost:6006/static/iframe.bundle.js:95423:26 at http://localhost:6006/static/iframe.bundle.js:96769:14`

**Comment by StevenFewster** [comment]
Please close.  Was setting my environment variables with "new " keyword proceeding them, which isn't necessary and was causing problems
