### ISSUE TITLE
Failing to compile

### ISSUE THREAD

**Issue by objectiveSee** [storybooks/storybook#4941]
**Describe the bug**
I am trying to install Storybook into an existing RN app. We do not use `expo` and we only have an `ios` app not `android` (yet). I am getting build errors when I run `yarn storybook` as well as `npm run storybook`. The compiler bug may be related to `babel-loader`. 

**To Reproduce**
1. Follow the instructions for adding a SB to a RN app.
2, When running `npm install` i get many unmet dependency warnings around SB and RN. See output: https://gist.github.com/objectiveSee/2d8ef1d5638f2de389e72515dd8bf044
3. After running storybook I get the following error:

```
ERROR in ./storybook/addons.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/username/workspace/MyProject/node_modules/babel-preset-react/lib/index.js
    at createDescriptor (/Users/username/workspace/MyProject/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
    at items.map (/Users/username/workspace/MyProject/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/username/workspace/MyProject/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/Users/username/workspace/MyProject/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at passPerPreset (/Users/username/workspace/MyProject/node_modules/@babel/core/lib/config/config-descriptors.js:58:96)
    at cachedFunction (/Users/username/workspace/MyProject/node_modules/@babel/core/lib/config/caching.js:33:19)
    at presets.presets (/Users/username/workspace/MyProject/node_modules/@babel/core/lib/config/config-descriptors.js:29:84)
    at mergeChainOpts (/Users/username/workspace/MyProject/node_modules/@babel/core/lib/config/config-chain.js:320:26)
    at /Users/username/workspace/MyProject/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at buildRootChain (/Users/username/workspace/MyProject/node_modules/@babel/core/lib/config/config-chain.js:68:29)
    at loadPrivatePartialConfig (/Users/username/workspace/MyProject/node_modules/@babel/core/lib/config/partial.js:85:55)
    at Object.loadPartialConfig (/Users/username/workspace/MyProject/node_modules/@babel/core/lib/config/partial.js:110:18)
    at Object.<anonymous> (/Users/username/workspace/MyProject/node_modules/babel-loader/lib/index.js:140:26)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/username/workspace/MyProject/node_modules/babel-loader/lib/index.js:3:103)
 @ multi ./storybook/addons.js ./node_modules/@storybook/react-native/dist/manager/index.js manager[0]
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  1.39 MiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core/src/server/templates/index.ejs] 1.62 KiB {HtmlWebpackPlugin_0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {HtmlWebpackPlugin_0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {HtmlWebpackPlugin_0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {HtmlWebpackPlugin_0} [built]
ℹ ｢wdm｣: Failed to compile.
```

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2015
 - Framework: react-native
 - Version: react-native-cli: 2.0.1
react-native: 0.57.7

**Comment by igor-dv** [comment]
This is a babel6 vs babel7 mismatch exception. @Gongreg, is there any workaround for this for now?

**Comment by objectiveSee** [comment]
@igor-dv We just created the React Native portion of our app this week so we can switch to using any version that works. Here's our package.json:


```
  "dependencies": {
    "expo": "31.0.5",
    "react": "16.6.3",
    "react-native": "0.57.7",
    "react-native-create-bridge": "2.0.1",
    "react-native-elements": "0.19.1",
    "react-native-fast-image": "^5.1.1",
    "react-native-linear-gradient": "2.5.2",
    "react-native-svg": "^8.0.8",
    "react-native-vector-icons": "^6.1.0"
  },
  "devDependencies": {
    "@storybook/react-native": "^4.0.12",
    "@storybook/addon-actions": "^4.0.12",
    "@storybook/addon-links": "^4.0.12",
    "@storybook/addons": "^4.0.12",
    "babel-core": "^6.26.3",
    "babel-runtime": "^6.26.0",
    "react-dom": "16.6.3",
    "prop-types": "^15.6.2"
  }
}

```

**Comment by igor-dv** [comment]
I think it's related to #4852

**Comment by bneigher** [comment]
this seems to be an issue with todays installs of react-native (0.57.8) and storybook/react-native (4.1.x and the 4.2.x releases). doing a fresh 

```
react-native init MyApp && cd MyApp &&
npx -p @storybook/cli sb init
```

can reproduce

**Comment by igor-dv** [comment]
It will be working after the #4942
