### ISSUE TITLE
Storyshots broken in 4.1.0-alpha.11

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#4964]
Transcribed from Discord:

```
    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/dev/Projects/.../node_modules/@storybook/addons/dist/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import "core-js/modules/es6.object.define-property";
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/api/index.js:10:39)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/index.js:52:35)
```

**Comment by shilman** [comment]
Fixed in https://github.com/storybooks/storybook/releases/tag/v4.1.0-alpha.12
