### ISSUE TITLE
Error in CLI with Vue support

### ISSUE THREAD

**Issue by kamontat** [storybooks/storybook#5019]
**Describe the bug**
Quick start with Storybook with Vue supported error.

**To Reproduce**
1. run `npx -p @storybook/cli sb init`
2. Choose `Vue`
3. See error

```
     TypeError: Cannot create property 'dependencies' on boolean 'false'
    at _callee$ (/Users/kamontat/.npm/_npx/94048/lib/node_modules/@storybook/cli/generators/VUE/index.js:33:3)
    at call (/Users/kamontat/.npm/_npx/94048/lib/node_modules/@storybook/cli/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.tryCatch [as _invoke] (/Users/kamontat/.npm/_npx/94048/lib/node_modules/@storybook/cli/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator._invoke [as next] (/Users/kamontat/.npm/_npx/94048/lib/node_modules/@storybook/cli/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Users/kamontat/.npm/_npx/94048/lib/node_modules/@storybook/cli/generators/VUE/index.js:34:103)
    at _next (/Users/kamontat/.npm/_npx/94048/lib/node_modules/@storybook/cli/generators/VUE/index.js:36:194)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Expected behavior**
Create project

**Screenshots**

<img width="1305" alt="screen shot 2018-12-17 at 15 29 33" src="https://user-images.githubusercontent.com/14089557/50093330-a4418380-0210-11e9-9170-7c21bd89135b.png">

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
 - OS: [e.g. iOS, Windows10, MacOS] MacOS
 - Device: [e.g. iPhoneX, Macbook Pro 2018] Macbook Pro 2015
 - Browser: [e.g. chrome, safari] chrome
 - Framework: [e.g. react, vue, angular] vue
 - Addons: [if relevant]
 - Version: [e.g. 4.0.0] cli version: `6.4.1`

**Additional context**

**Comment by LetoGear** [comment]
you need to prepare `package.json` first

**Comment by kamontat** [comment]
I see.

**Comment by kamontat** [comment]
You might need to add this into documentation.

**Comment by Lahirutech** [comment]
Can someone tell me the exact steps to setup storybooks

**Comment by bradley-varol** [comment]
@Lahirutech creating a `package.json` file and filling it with the following worked for me:
```json
{
  "scripts": {
    "storybook": "start-storybook"
  }
}
```

**Comment by adrianoresende** [comment]
1 - npm init
2 - npx -p @storybook/cli sb init --type vue

**Comment by shilman** [comment]
cc @ndelangen for #6002

**Comment by richsoni** [comment]
+1 just had to search to resolve this.  It would be really nice if the error said, "Do you have a package.json?"

**Comment by anevaude** [comment]
Can I delete the package.json after installing Storybook? I only made one to satisfy the install requirements, but I already have a main package.json in the parent folder, separate from the React-specific stuff.

**Comment by shilman** [comment]
@anevaude Can you just install it in the parent directory?

**Comment by anevaude** [comment]
> @anevaude Can you just install it in the parent directory?

@shilman - Oh yep! That's no problem at all. I just didn't know if it was "proper" to put it in the app directory itself. Some guides make it sound like that's the right way to go about things. :)
