### ISSUE TITLE
5.0.0-rc.3: Build crashes

### ISSUE THREAD

**Issue by TomiS** [storybooks/storybook#5687]
**Describe the bug**
Trying to start storybook crashes with error:

```
info @storybook/react v5.0.0-rc.3
info 
info => Loading presets
info => Loading presets
info => Loading custom addons config.
info => Using base config because react-scripts is not installed.

WARN Broken build, fix the error below.
WARN You may need to refresh the browser.

(node:3565) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'compilation' of undefined
    at buildDevStandalone (/home/xxx/my-app/node_modules/@storybook/core/dist/server/build-dev.js:347:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:3565) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3565) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


WARN Unable to close preview build!
```

**System:**
 - OS: Ubuntu 18.04
 - Framework: Webpack 4.19.1, React 16.8.1, Emotion 10.0.7
 - Version: 5.0.0-rc.3

**Storybook deps installed:**
```
    "@storybook/addon-a11y": "5.0.0-rc.3",
    "@storybook/addon-backgrounds": "5.0.0-rc.3",
    "@storybook/addon-info": "5.0.0-rc.3",
    "@storybook/addon-jest": "5.0.0-rc.3",
    "@storybook/addon-knobs": "5.0.0-rc.3",
    "@storybook/addon-links": "5.0.0-rc.3",
    "@storybook/addon-options": "5.0.0-rc.3",
    "@storybook/react": "5.0.0-rc.3",
```

**Comment by Kailaash-Balachandran** [comment]
You need to modify the webpack config as described here. In the migration step, there's a typo 
`config.modules` should be `config.module`

https://github.com/storybooks/storybook/blob/next/MIGRATION.md#from-version-41x-to-50x

**Comment by shilman** [comment]
@TomiS Closing for now. Please give the migration suggested by @Kailaash-Balachandran a try and re-open if you still have problems and we'll help get you sorted out. Thanks!
