### ISSUE TITLE
Unable to install storybook due to TypeError:

### ISSUE THREAD

**Issue by fauverism** [storybooks/storybook#5951]
**Describe the bug**
When running `npm install babel-cli babel-core --save-dev` then choosing *Yes* to _Do you want to manually choose a Storybook project type to install?_, then choosing *Angular* the following error occurs. 

```
     TypeError: Cannot read property 'babel-core' of undefined
    at _callee2$ (/Users/rfauve200/.npm/_npx/19992/lib/node_modules/@storybook/cli/lib/helpers.js:204:5)
    at call (/Users/rfauve200/.npm/_npx/19992/lib/node_modules/@storybook/cli/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.tryCatch [as _invoke] (/Users/rfauve200/.npm/_npx/19992/lib/node_modules/@storybook/cli/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator._invoke [as next] (/Users/rfauve200/.npm/_npx/19992/lib/node_modules/@storybook/cli/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Users/rfauve200/.npm/_npx/19992/lib/node_modules/@storybook/cli/lib/helpers.js:46:103)
    at _next (/Users/rfauve200/.npm/_npx/19992/lib/node_modules/@storybook/cli/lib/helpers.js:48:194)
    at /Users/rfauve200/.npm/_npx/19992/lib/node_modules/@storybook/cli/lib/helpers.js:48:364
    at new Promise (<anonymous>)
    at /Users/rfauve200/.npm/_npx/19992/lib/node_modules/@storybook/cli/lib/helpers.js:48:97
    at _installBabel (/Users/rfauve200/.npm/_npx/19992/lib/node_modules/@storybook/cli/lib/helpers.js:352:24)
```

**To Reproduce**
1. Go to Terminal
2. Run `npm install babel-cli babel-core --save-dev`
3. Choose *Yes* to _Do you want to manually choose a Storybook project type to install?_
4. Select *Angular*
5. Does not install storybook starter project

**Expected behavior**
Install storybook starter project

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2018
 - Framework: angular

**Additional context**

**Comment by rootical** [comment]
I have the same issue when installing angular version with:
`npx -p @storybook/cli sb init --type angular` any solution?
Thanks
