### ISSUE TITLE
required semicolons or commas for interfaces in stories

### ISSUE THREAD

**Issue by Stefanwullems** [storybooks/storybook#6416]
When defining an interface in a story, the build fails if the properties are not separated by either semicolons or commas. In normal files this works just fine.

**Comment by kroeder** [comment]
Can you provide more details? Which framework do you use? I assume you are using TypeScript? Can you provide a Code-Snippet or even better a reproduction example repository?

**Comment by Stefanwullems** [comment]
I stripped most unrelated things from our repository to still make the thing fail. [here's the repo](https://github.com/Stefanwullems/ts-storybook-interface-error )

**Comment by kroeder** [comment]
For the record - the stacktrace: 
```
WARNING in ./src/Component/Component.stories.tsx
Module build failed (from ./node_modules/@storybook/addon-storysource/loader.js):
SyntaxError: Unexpected token (11:3)
    at t (D:\04_Development\ts-storybook-interface-error\node_modules\prettier\parser-babylon.js:1:326)
    at Object.parse (D:\04_Development\ts-storybook-interface-error\node_modules\prettier\parser-babylon.js:1:208490)
    at Object.parse (D:\04_Development\ts-storybook-interface-error\node_modules\@storybook\addon-storysource\dist\loader\parsers\parser-js.js:13:47)
    at generateSourceWithDecorators (D:\04_Development\ts-storybook-interface-error\node_modules\@storybook\addon-storysource\dist\loader\generate-helpers.js:71:22)
    at inject (D:\04_Development\ts-storybook-interface-error\node_modules\@storybook\addon-storysource\dist\loader\inject-decorator.js:30:84)
    at Object.transform (D:\04_Development\ts-storybook-interface-error\node_modules\@storybook\addon-storysource\dist\loader\index.js:18:47)
 @ ./src sync .stories.(js|tsx)$ ./Component/Component.stories.tsx
 @ ./docs/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./docs/config.js ./node_modules/webpack-hot-middleware/client.js?reload=true
```

addon-storysource causes it (as you can see in the stacktrace)

```const path = require('path')

module.exports = async ({ config }) => {

  // Storysource
  config.module.rules.push({
    test: /\.stories\.tsx?$/,
    loaders: [
      require.resolve('@storybook/addon-storysource/loader')
    ],
    enforce: 'pre'
  })

  return config
}
```

Removing the storysource code in `webpack.config.js` resolves the error.
It has a workaround.
```typescript
interface Interface {
  test1: string;
  test2: string;
}
```

Good catch 👍

**Comment by shilman** [comment]
Note: we are moving to `@storybook/source-loader` in 5.2 which may have solved this issue since Typescript handling has been rewritten by @libetl
