### ISSUE TITLE
Migration to 5.1.0-alpha.24 fail

### ISSUE THREAD

**Issue by feonit** [storybooks/storybook#6465]
I try migrate from 4.1.11 to 5.1.0-alpha.24 and did catch this:

**Describe the bug**
```
ModuleBuildError: Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /Users/feonit/github/demo_ui/.storybook/addons.js: Cannot find module '@babel/helper-create-class-features-plugin' (While processing: "/Users/feonit/github/demo_ui/node_modules/@storybook/core/node_modules/@babel/plugin-proposal-class-properties/lib/index.js")
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

**System:**
 - OS: [MacOS]

**Comment by shilman** [comment]
Are you using custom babel/webpack?

**Comment by feonit** [comment]
no, cra2

**Comment by feonit** [comment]
nevermind, 5.1.0-rc.0 is successfully installed

**Comment by ndelangen** [comment]
Thanks for reporting back @feonit 💪
