### ISSUE TITLE
Storybook doesn't work for nodejs 7.2.1

### ISSUE THREAD

**Issue by zhaoyi0113** [storybooks/storybook#6510]
When I tried to add storybook on a react application. I got below error. It is caused by the nodejs I am using doesn't support `async` syntax. I have configured `babel` and `webpack` to transpile the code but it doesn't seem to work. How can I make storybook work for node7?

```
TheFrontEnd/node_modules/@storybook/core/dist/server/build-static.js:31
async function compileManager(managerConfig, managerStartTime) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

**Comment by shilman** [comment]
@zhaoyi0113 Unfortunately we have a node requirement of 8.6 and above:

https://github.com/storybooks/storybook/blob/next/package.json#L190-L193
