### ISSUE TITLE
Addon-docs: DocsPage fails unless a theme is specified

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#6903]
When you add DocsPage from `addon-docs` to a storybook that does not use themes, e.g. https://github.com/grommet/grommet, it fails with a stack trace like this:

```
Cannot read property 'content' of undefined
TypeError: Cannot read property 'content' of undefined
    at http://localhost:9001/vendors~main.c8b4f2daa76858521d54.bundle.js:8420:34
    at handleInterpolation (http://localhost:9001/vendors~main.c8b4f2daa76858521d54.bundle.js:597:24)
    at serializeStyles (http://localhost:9001/vendors~main.c8b4f2daa76858521d54.bundle.js:682:15)
    at http://localhost:9001/vendors~main.c8b4f2daa76858521d54.bundle.js:994:100
    at updateContextConsumer (http://localhost:9001/vendors~main.c8b4f2daa76858521d54.bundle.js:104878:19)
    at beginWork (http://localhost:9001/vendors~main.c8b4f2daa76858521d54.bundle.js:105066:14)
    at performUnitOfWork (http://localhost:9001/vendors~main.c8b4f2daa76858521d54.bundle.js:108706:12)
    at workLoop (http://localhost:9001/vendors~main.c8b4f2daa76858521d54.bundle.js:108746:24)
    at renderRoot (http://localhost:9001/vendors~main.c8b4f2daa76858521d54.bundle.js:108829:7)
    at performWorkOnRoot (http://localhost:9001/vendors~main.c8b4f2daa76858521d54.bundle.js:109736:7)
```

DocsPage (or its container?) needs to ensure that a theme is provided so that its Doc Blocks can use the theme.

As a temporary workaround you can simply add a theme in `config.js`:

```js
import { addParameters } from '@storybook/react';
import { themes } from '@storybook/theming';
addParameters({ options: { theme: themes.light }});
```

**Comment by shilman** [comment]
Turns out this was an unrelated bug solved in https://github.com/storybooks/storybook/commit/1ee3302400f8a85978e88c13cec0c51182e607d2

**Comment by Domiii** [comment]
@shilman This error is popping up again, due to https://github.com/storybookjs/storybook/issues/13145.
