### ISSUE TITLE
Add support to NWB

### ISSUE THREAD

**Issue by sbehrends** [storybooks/storybook#692]
Add "getstorybook" support for NWB react-apps
https://github.com/insin/nwb

It's a good alternative for create-react-app.

**Comment by ndelangen** [comment]
What doesn't work currently? This is the first of me hearing about NWB, so if you can help me understand how the experience is now, and what you'd like to have changed, that'd be super helpful 💯

**Comment by ndelangen** [comment]
It's very much welcome, if someone wants to contribute in any way to make this happen, Ping me if you need help! I think it's doable to add to our CLI!

**Comment by ryanlanciaux** [comment]
For what it's worth -- this worked for me with 0 trouble what-so-ever.

I took the following steps

1. created a component with nwb through the nwb cli.
1. added storybook to the project (`npm i -g @storybook/cli && getstorybook` in the project directory)
1. Added something like the code block below to stores/index.js

```
import DefaultThing from '../src';
storiesOf('DefaultThing', module)
  .add('it seems to be working 👍', () => <DefaultThing />);
```

Is there something specifically that's not working with this setup? 👍  If there is I'd like to dig into it a bit more and see if that helps.

**Comment by ndelangen** [comment]
I'm closing this issue as there seems to be nothing actionable for us to do for now. Please re-open if there are any issues.

Thanks @ryanlanciaux for testing 👏

**Comment by greatwitenorth** [comment]
It looks like NWB and Storybook do not play well together anymore. I'm currently using the following:

nwb: v0.23.0
storybook: v3.4.11

I run the following commands:
```
nwb new react-component testing
cd testing
getstorybook
npm start
```

and I see the following error:

```
⋊> ~/testing on master ⨯ npm start                                                                                                                                      12:43:56

> testing@1.0.0 start /Users/nickv/testing
> nwb serve-react-demo

Error running command: Cannot destructure property `createHash` of 'undefined' or 'null'.
TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.
    at Object.<anonymous> (/Users/nickv/testing/node_modules/mini-css-extract-plugin/dist/index.js:26:44)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/nickv/testing/node_modules/mini-css-extract-plugin/dist/cjs.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testing@1.0.0 start: `nwb serve-react-demo`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the testing@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nickv/.npm/_logs/2018-10-19T17_44_04_032Z-debug.log
```

Not sure what to do from here.

**Comment by ndelangen** [comment]
@greatwitenorth please try the latest release candidate?

I think you're hitting a webpack version mismatch. RC releases use webpack 4 & babel 7.
