### ISSUE TITLE
CSS import not supported on ejected create-react-app

### ISSUE THREAD

**Issue by coryhouse** [storybooks/storybook#738]
Importing CSS works great for an *unejected* app created via create-react-app. But if you eject, storybook throws an error when importing CSS:

Steps to reproduce:
1. create-react-app myapp
2. cd myapp
3. npm run eject
4. getstorybook
5. create a plain css file
6. import css file into a storybook story like this: `import './styles.css';`

Receive the following:

```
Module parse failed: /Users/cory/Desktop/myapp/stories/button.css Unexpected token (1:5)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:5)
    at Parser.pp$4.raise (/Users/cory/Desktop/myapp/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/cory/Desktop/myapp/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Users/cory/Desktop/myapp/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Users/cory/Desktop/myapp/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/Users/cory/Desktop/myapp/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseTopLevel (/Users/cory/Desktop/myapp/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/cory/Desktop/myapp/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/cory/Desktop/myapp/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/cory/Desktop/myapp/node_modules/webpack/lib/Parser.js:902:15)
    at NormalModule.<anonymous> (/Users/cory/Desktop/myapp/node_modules/webpack/lib/NormalModule.js:104:16)
 @ ./stories/Button.js 12:0-23
```

[Here's a repo that reproduces the issue](https://github.com/coryhouse/storybook-css-bug). Note that create-react-app was simply installed and ejected. No other changes made.

**Comment by tmeasday** [comment]
Thanks for the repro @coryhouse!

I copied over some basic webpack config from CRA's `webpack.config` and it works fine of course:

https://github.com/tmeasday/storybook-css-bug/commit/f8a96c17c4e81b1a0b4eba2818f0fff48cd3563e

I wonder what it is about ejecting that make you need to do this?

**Comment by tmeasday** [comment]
Oh, it also works fine if you remove `.storybook/webpack.config.js`. That file is automatically added by `getstorybook`, but as it says [here](https://getstorybook.io/docs/react-storybook/configurations/custom-webpack-config) if you create that file, it doesn't use the default webpack config.

I wonder why getstorybook adds that (more or less empty) file.

**Comment by inactivist** [comment]
Confirming @tmeasday [fix](https://github.com/storybooks/react-storybook/issues/738#issuecomment-292846116) works here

**Comment by ndelangen** [comment]
Yeah this is an odd bug:
https://github.com/coryhouse/storybook-css-bug/blob/master/.storybook/webpack.config.js
