### ISSUE TITLE
storyshots example not working only leads to error

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#890]
<a href="https://github.com/radosch"><img src="https://avatars0.githubusercontent.com/u/339111?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [radosch](https://github.com/radosch)**
_Monday Mar 20, 2017 at 12:53 GMT_
_Originally opened as https://github.com/storybooks/storyshots/issues/88_

----

 FAIL  ./Storyshots.test.js Test suite failed to run

    Cannot find module '../../package' from 'node.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (node_modules/babel-core/lib/api/node.js:60:16)

anyone has a clue / hint if this is a failure of implementation or a bug?
thnx a lot!

**Comment by shilman** [comment]
<a href="https://github.com/eric-burel"><img src="https://avatars2.githubusercontent.com/u/7983005?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [eric-burel](https://github.com/eric-burel)**
_Tuesday Apr 11, 2017 at 10:38 GMT_

----

Don't forget to add json as a valid module extension in your jest config:
`
    "moduleFileExtensions": [
      "js", "jsx", "ts", "tsx", "json"
    ],
`
Indeed you can see in `babel-core` code that it loads the root `package.json` file.
