### ISSUE TITLE
working with generate react component

### ISSUE THREAD

**Issue by maxlibin** [storybooks/storybook#970]
installing storybook in https://github.com/JedWatson/generator-react-component gets an error:

```
ERROR in ./.storybook/config.js
Module build failed: ReferenceError: [BABEL] /Users/max/workspace/react-component/packages/style-react-component/.storybook/config.js: Unknown option: direct.presets
    at Logger.error (/Users/max/workspace/react-component/packages/style-react-component/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/Users/max/workspace/react-component/packages/style-react-component/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.init (/Users/max/workspace/react-component/packages/style-react-component/node_modules/babel-core/lib/transformation/file/options/option-manager.js:216:10)
    at File.initOptions (/Users/max/workspace/react-component/packages/style-react-component/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/Users/max/workspace/react-component/packages/style-react-component/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/Users/max/workspace/react-component/packages/style-react-component/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/Users/max/workspace/react-component/packages/style-react-component/node_modules/babel-loader/lib/index.js:46:20)
    at /Users/max/workspace/react-component/packages/style-react-component/node_modules/babel-loader/lib/fs-cache.js:79:18
    at ReadFileContext.callback (/Users/max/workspace/react-component/packages/style-react-component/node_modules/babel-loader/lib/fs-cache.js:15:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
 @ multi preview
```

anyway to work with this package?

**Comment by mskec** [comment]
I have the same problem. I think the problem is in this library which was updated yesterday.
https://github.com/xzyfer/sass-graph/issues/77

**Comment by xzyfer** [comment]
Apologies for the break. We've unpublished the broken version.

**Comment by shilman** [comment]
@maxlibin @mskec does this work with the updated version mentioned above?

**Comment by mskec** [comment]
@shilman I didn't get this error while using storybook. I got here by googling error message :)
Since broken version was unpublished, I am no longer getting this error in my project. I guess storybook should also work, maybe @maxlibin can confirm.

**Comment by maxlibin** [comment]
uninstall and reinstall storybook in this package, still not working,
